import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Calendar, ChevronRight, Download, Search, Trash2 } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { downloadExport, getMeeting, getMeetings, post, remove } from "../lib/api";

export function History(){const meetings=useQuery({queryKey:["meetings"],queryFn:getMeetings});const [filter,setFilter]=useState("");const rows=meetings.data?.filter(item=>item.title.toLowerCase().includes(filter.toLowerCase()))??[];return <div className="page"><header className="page-head"><div><p className="eyebrow">ARCHIVE</p><h1>會議歷史</h1><p>檢視逐字稿、決策、Codex runs 與匯出。</p></div><div className="search large"><Search/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="依標題搜尋"/></div></header><div className="meeting-table"><div className="table-head"><span>會議</span><span>狀態</span><span>開始時間</span><span>語言</span><span/></div>{rows.map(item=><Link to={`/history/${item.id}`} key={item.id}><div><strong>{item.title}</strong><small>{item.goal}</small></div><span className={`status-label ${item.status}`}>{item.status}</span><span>{item.started_at?new Date(item.started_at).toLocaleString():"尚未開始"}</span><span>{item.language}</span><ChevronRight/></Link>)}{rows.length===0&&<div className="empty"><Calendar/><strong>找不到會議</strong></div>}</div></div>}

export function HistoryDetail(){const {id=""}=useParams();const navigate=useNavigate();const client=useQueryClient();const detail=useQuery({queryKey:["meeting",id],queryFn:()=>getMeeting(id)});const [tab,setTab]=useState("transcript");const data=detail.data;if(!data)return <div className="page"><div className="empty">載入中</div></div>;const removeMeeting=async()=>{if(!confirm("完整刪除此會議、逐字稿與事件？"))return;await remove(`/meetings/${id}`);await client.invalidateQueries({queryKey:["meetings"]});navigate("/history")};return <div className="page"><header className="page-head"><div><p className="eyebrow">MEETING DETAIL · {data.meeting.status}</p><h1>{data.meeting.title}</h1><p>{data.meeting.goal}</p></div><div className="head-actions"><button className="button" onClick={()=>void post(`/meetings/${id}/analyze`)}>重新分析</button><button className="icon-button danger" title="刪除會議" onClick={()=>void removeMeeting()}><Trash2/></button></div></header><div className="detail-summary"><div><span>逐字稿</span><strong>{data.transcripts.length}</strong></div><div><span>建議接受率</span><strong>{data.suggestions.length?`${Math.round(data.suggestions.filter(x=>x.status==="accepted").length/data.suggestions.length*100)}%`:"—"}</strong></div><div><span>Codex runs</span><strong>{data.codex_runs.length}</strong></div><div><span>行動項目</span><strong>{data.action_items.length}</strong></div></div><div className="tabs">{["transcript","suggestions","state","codex"].map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div><section className="detail-content">{tab==="transcript"&&data.transcripts.map(item=><div className="detail-row" key={item.id}><time>{(item.start_ms/1000).toFixed(1)}s</time><p>{item.text}</p></div>)}{tab==="suggestions"&&data.suggestions.map(item=><div className="detail-row" key={item.id}><span>{item.category}</span><p>{item.content}</p><strong>{item.status}</strong></div>)}{tab==="state"&&[["Decisions",data.decisions],["Open questions",data.open_questions],["Risks",data.risks],["Actions",data.action_items]].map(([name,items])=><div className="state-group" key={String(name)}><h3>{String(name)}</h3>{Array.isArray(items)&&items.map(item=><p key={String(item.id)}>{String(item.content)}</p>)}</div>)}{tab==="codex"&&data.codex_runs.map(run=><div className="detail-row" key={String(run.id)}><code>{String(run.id).slice(0,8)}</code><p>{String(run.job_type)} · {String(run.trigger)}</p><strong>{String(run.status)}</strong><small>{String(run.sanitized_stderr||"")}</small></div>)}</section><div className="export-bar"><Download/><strong>匯出</strong>{(["markdown","json","vtt"] as const).map(format=><button className="button" onClick={()=>void downloadExport(id,format)} key={format}>{format.toUpperCase()}</button>)}<button className="button danger" onClick={()=>confirm("刪除已保存的音訊？")&&void remove(`/meetings/${id}/audio`)}>僅刪除音訊</button></div></div>}
