import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, CircleAlert, FilePlus2, GitCompare, ListTodo, Search, Trash2, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { useDialogs } from "../components/DialogProvider";
import {
  ActionItem,
  Decision,
  KnowledgeSearchResult,
  Meeting,
  Project,
  getActions,
  getDecisions,
  getMeetings,
  getProjects,
  post,
  put,
  remove,
  searchKnowledge,
} from "../lib/api";

const decisionStatuses = ["draft", "proposed", "confirmed", "rejected", "superseded", "archived"] as const;
const actionStatuses = ["open", "in_progress", "blocked", "completed", "archived"] as const;
const priorities = ["low", "normal", "high", "urgent"] as const;

type DecisionForm = {meeting_id:string;project_id:string;title:string;description:string;owner:string;status:Decision["status"];confidence:number;evidence_segment_ids:string[]};
const emptyDecision: DecisionForm = {meeting_id:"",project_id:"",title:"",description:"",owner:"",status:"draft",confidence:1,evidence_segment_ids:[]};

export function Decisions(){
  const client=useQueryClient(); const projects=useQuery({queryKey:["projects"],queryFn:getProjects}); const meetings=useQuery({queryKey:["meetings"],queryFn:getMeetings});
  const [q,setQ]=useState(""); const [project,setProject]=useState(""); const [status,setStatus]=useState(""); const [owner,setOwner]=useState("");
  const params=new URLSearchParams(); if(q)params.set("q",q);if(project)params.set("project_id",project);if(status)params.set("status",status);if(owner)params.set("owner",owner);
  const query=`?${params}`; const decisions=useQuery({queryKey:["decisions",query],queryFn:()=>getDecisions(query)});
  const [editing,setEditing]=useState<Decision|null|undefined>(); const [form,setForm]=useState<DecisionForm>(emptyDecision); const [selected,setSelected]=useState<Decision|null>(null); const [error,setError]=useState("");
  const open=(row?:Decision)=>{setEditing(row??null);setForm(row?{meeting_id:row.meeting_id,project_id:row.project_id??"",title:row.title,description:row.description,owner:row.owner??"",status:row.status,confidence:row.confidence,evidence_segment_ids:row.evidence_segment_ids_json}:emptyDecision);setError("")};
  const save=async(event:FormEvent)=>{event.preventDefault();setError("");const payload={...form,project_id:form.project_id||null,owner:form.owner||null};try{if(editing)await put(`/decisions/${editing.id}`,payload);else await post("/decisions",payload);setEditing(undefined);await client.invalidateQueries({queryKey:["decisions"]})}catch(reason){setError(reason instanceof Error?reason.message:"儲存失敗")}};
  const command=async(row:Decision,action:"confirm"|"reject")=>{await post(`/decisions/${row.id}/${action}`);setSelected(null);await client.invalidateQueries({queryKey:["decisions"]})};
  const lineage=(decisions.data??[]).filter(row=>selected&&(row.id===selected.supersedes_id||row.id===selected.superseded_by_id));
  return <div className="page"><header className="page-head"><div><p className="eyebrow">DECISION HISTORY</p><h1>決策時間軸</h1><p>保留每一版決策、來源會議與狀態轉換。</p></div><button className="button primary" onClick={()=>open()}><FilePlus2 size={16}/>新增決策</button></header>
    <div className="work-filter"><div className="search large"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋標題或內容"/></div><select value={project} onChange={e=>setProject(e.target.value)}><option value="">所有專案</option>{projects.data?.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">所有狀態</option>{decisionStatuses.map(value=><option key={value}>{value}</option>)}</select><input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="負責人"/></div>
    <div className="timeline-list">{decisions.data?.map(row=><article key={row.id} className={`work-row ${row.status}`}><button className="row-main" onClick={()=>setSelected(row)}><span className="timeline-mark"/><span><strong>{row.title||row.description}</strong><small>{row.description}</small></span><code>v{row.version}</code><span className="status-label">{row.status}</span><time>{new Date(row.created_at).toLocaleString()}</time></button><div className="row-actions">{!(["confirmed","rejected","superseded","archived"] as string[]).includes(row.status)&&<><button title="確認決策" onClick={()=>void command(row,"confirm")}><Check/></button><button title="拒絕決策" onClick={()=>void command(row,"reject")}><X/></button></>} {!(["superseded","archived"] as string[]).includes(row.status)&&<button title="建立新版" onClick={()=>open(row)}><GitCompare/></button>}</div></article>)}{!decisions.isPending&&!decisions.data?.length&&<div className="empty"><GitCompare/><strong>沒有符合的決策</strong></div>}</div>
    {selected&&<div className="modal-backdrop"><section className="modal"><header><h2>{selected.title}</h2><button className="icon-button" title="關閉" onClick={()=>setSelected(null)}><X/></button></header><dl className="record-detail"><div><dt>狀態</dt><dd>{selected.status}</dd></div><div><dt>版本</dt><dd>v{selected.version}</dd></div><div><dt>負責人</dt><dd>{selected.owner||"未指派"}</dd></div><div><dt>信心</dt><dd>{Math.round(selected.confidence*100)}%</dd></div><div className="wide"><dt>內容</dt><dd>{selected.description}</dd></div><div className="wide"><dt>來源會議</dt><dd>{meetings.data?.find(row=>row.id===selected.meeting_id)?.title??selected.meeting_id}</dd></div></dl>{lineage.length>0&&<div className="version-compare"><h3>相鄰版本</h3>{lineage.map(row=><button key={row.id} onClick={()=>setSelected(row)}>v{row.version} · {row.title} · {row.status}</button>)}</div>}<footer><button className="button" onClick={()=>{setSelected(null);open(selected)}}><GitCompare size={15}/>建立新版</button></footer></section></div>}
    {editing!==undefined&&<DecisionEditor row={editing} form={form} setForm={setForm} meetings={meetings.data??[]} projects={projects.data??[]} error={error} close={()=>setEditing(undefined)} save={save}/>}</div>
}

function DecisionEditor({row,form,setForm,meetings,projects,error,close,save}:{row:Decision|null;form:DecisionForm;setForm:(value:DecisionForm)=>void;meetings:Meeting[];projects:Project[];error:string;close:()=>void;save:(event:FormEvent)=>Promise<void>}){
  const chooseMeeting=(id:string)=>{const meeting=meetings.find(item=>item.id===id);setForm({...form,meeting_id:id,project_id:meeting?.project_id??""})};
  return <div className="modal-backdrop"><form className="modal" onSubmit={event=>void save(event)}><header><h2>{row?`建立 v${row.version+1}`:"新增決策"}</h2><button type="button" className="icon-button" title="關閉" onClick={close}><X/></button></header><div className="form-grid"><label>來源會議<select required disabled={Boolean(row)} value={form.meeting_id} onChange={e=>chooseMeeting(e.target.value)}><option value="">選擇會議</option>{meetings.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>專案<select disabled value={form.project_id}><option value="">無專案</option>{projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="wide">標題<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide">說明<textarea rows={6} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>負責人<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>狀態<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Decision["status"]})}>{decisionStatuses.filter(value=>!row||!["superseded","archived"].includes(value)).map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">信心值 <output>{Math.round(form.confidence*100)}%</output><input type="range" min="0" max="1" step="0.05" value={form.confidence} onChange={e=>setForm({...form,confidence:Number(e.target.value)})}/></label></div>{error&&<div className="alert error">{error}</div>}<footer><button type="button" className="button" onClick={close}>取消</button><button className="button primary">{row?"建立新版":"儲存"}</button></footer></form></div>
}

type ActionForm={meeting_id:string;project_id:string;title:string;description:string;owner:string;due_at:string;priority:ActionItem["priority"];status:ActionItem["status"];linked_decision_id:string;evidence_segment_ids:string[]};
const emptyAction:ActionForm={meeting_id:"",project_id:"",title:"",description:"",owner:"",due_at:"",priority:"normal",status:"open",linked_decision_id:"",evidence_segment_ids:[]};

export function Actions(){
  const dialogs=useDialogs();
  const client=useQueryClient();const meetings=useQuery({queryKey:["meetings"],queryFn:getMeetings});const projects=useQuery({queryKey:["projects"],queryFn:getProjects});const decisions=useQuery({queryKey:["decisions","actions"],queryFn:()=>getDecisions()});const actions=useQuery({queryKey:["actions"],queryFn:()=>getActions()});
  const [view,setView]=useState("all");const [q,setQ]=useState("");const [editing,setEditing]=useState<ActionItem|null|undefined>();const [form,setForm]=useState<ActionForm>(emptyAction);const [error,setError]=useState("");const mine=localStorage.getItem("meeting-copilot-owner")??"";const now=Date.now();
  const rows=useMemo(()=>(actions.data??[]).filter(row=>`${row.title} ${row.description} ${row.owner}`.toLowerCase().includes(q.toLowerCase())).filter(row=>{const due=row.due_at?new Date(row.due_at).getTime():0;if(view==="mine")return Boolean(mine)&&row.owner===mine;if(view==="overdue")return due>0&&due<now&&!(["completed","archived"] as string[]).includes(row.status);if(view==="due_soon")return due>=now&&due<=now+7*86400000;if(["in_progress","blocked","completed"].includes(view))return row.status===view;return view==="all"}),[actions.data,q,view,mine,now]);
  const open=(row?:ActionItem)=>{setEditing(row??null);setForm(row?{meeting_id:row.meeting_id,project_id:row.project_id??"",title:row.title,description:row.description,owner:row.owner??"",due_at:row.due_at?new Date(row.due_at).toISOString().slice(0,16):"",priority:row.priority,status:row.status,linked_decision_id:row.linked_decision_id??"",evidence_segment_ids:row.evidence_segment_ids_json}:emptyAction);setError("")};
  const save=async(event:FormEvent)=>{event.preventDefault();setError("");const payload={...form,project_id:form.project_id||null,owner:form.owner||null,due_at:form.due_at?new Date(form.due_at).toISOString():null,linked_decision_id:form.linked_decision_id||null};try{if(editing)await put(`/actions/${editing.id}`,payload);else await post("/actions",payload);setEditing(undefined);await client.invalidateQueries({queryKey:["actions"]})}catch(reason){setError(reason instanceof Error?reason.message:"儲存失敗")}};
  const destroy=async(row:ActionItem)=>{if(!await dialogs.confirm({title:"刪除行動項目",message:`刪除行動項目「${row.title}」？`,confirmLabel:"刪除",danger:true}))return;await remove(`/actions/${row.id}`);await client.invalidateQueries({queryKey:["actions"]})};
  const quickStatus=async(row:ActionItem,status:ActionItem["status"])=>{await put(`/actions/${row.id}`,{meeting_id:row.meeting_id,project_id:row.project_id,title:row.title,description:row.description,owner:row.owner,due_at:row.due_at,priority:row.priority,status,linked_decision_id:row.linked_decision_id,evidence_segment_ids:row.evidence_segment_ids_json});await client.invalidateQueries({queryKey:["actions"]})};
  return <div className="page"><header className="page-head"><div><p className="eyebrow">ACTION TRACKER</p><h1>行動項目</h1><p>依負責人、期限、優先度與狀態追蹤工作。</p></div><button className="button primary" onClick={()=>open()}><FilePlus2 size={16}/>新增項目</button></header><div className="view-tabs">{["all","mine","overdue","due_soon","in_progress","blocked","completed"].map(value=><button className={view===value?"active":""} onClick={()=>setView(value)} key={value}>{value.replaceAll("_"," ")}</button>)}</div><div className="work-filter"><div className="search large"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋工作或負責人"/></div><span>{rows.length} 項</span></div><div className="action-table"><div className="action-head"><span>工作</span><span>負責人</span><span>到期</span><span>優先度</span><span>狀態</span><span/></div>{rows.map(row=><div className="action-row" key={row.id}><button className="action-title" onClick={()=>open(row)}><strong>{row.title}</strong><small>{row.description}</small></button><span>{row.owner||"未指派"}</span><time className={row.due_at&&new Date(row.due_at).getTime()<now&&row.status!=="completed"?"overdue":""}>{row.due_at?new Date(row.due_at).toLocaleDateString():"—"}</time><code>{row.priority}</code><select aria-label={`${row.title} 狀態`} value={row.status} onChange={e=>void quickStatus(row,e.target.value as ActionItem["status"])}>{actionStatuses.map(value=><option key={value}>{value}</option>)}</select><button className="icon-button danger" title="刪除" onClick={()=>void destroy(row)}><Trash2 size={14}/></button></div>)}{!rows.length&&<div className="empty"><ListTodo/><strong>此檢視沒有行動項目</strong></div>}</div>
    {editing!==undefined&&<div className="modal-backdrop"><form className="modal" onSubmit={event=>void save(event)}><header><h2>{editing?"編輯行動項目":"新增行動項目"}</h2><button type="button" className="icon-button" title="關閉" onClick={()=>setEditing(undefined)}><X/></button></header><div className="form-grid"><label>來源會議<select required value={form.meeting_id} onChange={e=>{const meeting=meetings.data?.find(row=>row.id===e.target.value);setForm({...form,meeting_id:e.target.value,project_id:meeting?.project_id??"",linked_decision_id:""})}}><option value="">選擇會議</option>{meetings.data?.map(row=><option value={row.id} key={row.id}>{row.title}</option>)}</select></label><label>專案<select disabled value={form.project_id}><option value="">無專案</option>{projects.data?.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label className="wide">標題<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide">說明<textarea rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>負責人<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>到期日<input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>優先度<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as ActionItem["priority"]})}>{priorities.map(value=><option key={value}>{value}</option>)}</select></label><label>狀態<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ActionItem["status"]})}>{actionStatuses.map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">連結決策<select value={form.linked_decision_id} onChange={e=>setForm({...form,linked_decision_id:e.target.value})}><option value="">未連結</option>{decisions.data?.filter(row=>row.meeting_id===form.meeting_id).map(row=><option value={row.id} key={row.id}>v{row.version} · {row.title}</option>)}</select></label></div>{error&&<div className="alert error">{error}</div>}<footer><button type="button" className="button" onClick={()=>setEditing(undefined)}>取消</button><button className="button primary">儲存</button></footer></form></div>}</div>
}

export function Knowledge(){
  const dialogs=useDialogs();
  const client=useQueryClient();const projects=useQuery({queryKey:["projects"],queryFn:getProjects});const [q,setQ]=useState("");const [project,setProject]=useState("");const [source,setSource]=useState("");const [submitted,setSubmitted]=useState("");const params=new URLSearchParams();params.set("q",submitted);if(project)params.set("project_id",project);if(source)params.set("source_type",source);const key=`?${params}`;const results=useQuery({queryKey:["knowledge",key],queryFn:()=>searchKnowledge(key)});
  const [creating,setCreating]=useState(false);const [preview,setPreview]=useState<KnowledgeSearchResult|null>(null);const [form,setForm]=useState({project_id:"",source_type:"uploaded",title:"",content:"",language:"zh-TW",metadata:{}});const [error,setError]=useState("");
  const save=async(event:FormEvent)=>{event.preventDefault();setError("");try{await post("/knowledge/documents",{...form,project_id:form.project_id||null});setCreating(false);setSubmitted(form.title);setQ(form.title);await client.invalidateQueries({queryKey:["knowledge"]})}catch(reason){setError(reason instanceof Error?reason.message:"新增失敗")}};
  const destroy=async(row:KnowledgeSearchResult)=>{if(row.source_type!=="document"||!await dialogs.confirm({title:"刪除知識文件",message:`刪除文件「${row.title}」及其索引內容？`,confirmLabel:"刪除",danger:true}))return;await remove(`/knowledge/documents/${row.id}`);setPreview(null);await client.invalidateQueries({queryKey:["knowledge"]})};
  return <div className="page"><header className="page-head"><div><p className="eyebrow">KNOWLEDGE BASE</p><h1>知識庫</h1><p>搜尋會議、逐字稿、決策、任務、專案記憶與文件。</p></div><button className="button primary" onClick={()=>setCreating(true)}><FilePlus2 size={16}/>新增文件</button></header><form className="knowledge-search" onSubmit={e=>{e.preventDefault();setSubmitted(q)}}><div className="search large"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋全部知識來源"/></div><select value={project} onChange={e=>setProject(e.target.value)}><option value="">所有專案</option>{projects.data?.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option value="">所有來源</option>{["document","meeting","transcript","decision","action","risk","question","project_memory"].map(value=><option key={value}>{value}</option>)}</select><button className="button primary">搜尋</button></form><div className="knowledge-results">{results.data?.map(row=><button key={`${row.source_type}-${row.id}`} onClick={()=>setPreview(row)}><span className="source-badge">{row.source_type}</span><span><strong>{row.title}</strong><small>{row.excerpt||"沒有摘要"}</small></span><time>{new Date(row.created_at).toLocaleDateString()}</time></button>)}{!results.isPending&&!results.data?.length&&<div className="empty"><Search/><strong>找不到符合的知識</strong></div>}</div>
    {preview&&<div className="modal-backdrop"><section className="modal"><header><div><span className="source-badge">{preview.source_type}</span><h2>{preview.title}</h2></div><button className="icon-button" title="關閉" onClick={()=>setPreview(null)}><X/></button></header><p className="document-preview">{preview.excerpt}</p><dl className="record-detail"><div><dt>語言</dt><dd>{preview.language}</dd></div><div><dt>狀態</dt><dd>{preview.status||"—"}</dd></div><div><dt>建立日期</dt><dd>{new Date(preview.created_at).toLocaleString()}</dd></div></dl><footer>{preview.source_type==="document"&&<button className="button danger" onClick={()=>void destroy(preview)}><Trash2 size={15}/>刪除文件</button>}</footer></section></div>}
    {creating&&<div className="modal-backdrop"><form className="modal" onSubmit={event=>void save(event)}><header><h2>新增知識文件</h2><button type="button" className="icon-button" title="關閉" onClick={()=>setCreating(false)}><X/></button></header><div className="form-grid"><label>專案<select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">全域知識</option>{projects.data?.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label>語言<select value={form.language} onChange={e=>setForm({...form,language:e.target.value})}>{["zh-TW","zh-CN","en","ja","ko"].map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">標題<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide">內容<textarea required rows={14} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label></div>{error&&<div className="alert error"><CircleAlert size={15}/>{error}</div>}<footer><button type="button" className="button" onClick={()=>setCreating(false)}>取消</button><button className="button primary">建立索引</button></footer></form></div>}</div>
}
