import { useQuery } from "@tanstack/react-query";
import { Mic, Play, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { LanguageCode, Meeting, getProjects, getProviders, getSettings, post } from "../lib/api";
import { useMicrophone } from "../hooks/useMicrophone";

const languages:Array<[LanguageCode,string]>=[["zh-TW","繁體中文"],["zh-CN","简体中文"],["en","English"],["ja","日本語"],["ko","한국어"]];
const defaults={project_id:"",title:"",goal:"",language:"auto",secondary_language:"none",transcript_display_language:"original",translation_language:"none",analysis_language_mode:"original",suggestion_language:"zh-TW",summary_language:"zh-TW",export_language:"original",tts_language:"zh-TW",tts_voice:"",tts_rate:1,tts_volume:1,stt_provider_id:"local-stt-primary",tts_provider_id:"browser-tts",codex_profile:"",analysis_engine:"codex",automatic_analysis_enabled:true,analysis_interval_seconds:120,suggestion_cooldown_seconds:180,human_approval_before_speech:true,save_audio:false,repository_context_enabled:false,repository_path:"",repository_read_only:true,reference_notes:"",participants:"",privacy_acknowledged:false};

export function MeetingPrep(){
  const navigate=useNavigate();const [params]=useSearchParams();const providers=useQuery({queryKey:["providers"],queryFn:getProviders});const projects=useQuery({queryKey:["projects"],queryFn:getProjects});const settings=useQuery({queryKey:["settings"],queryFn:getSettings});const mic=useMicrophone();const [form,setForm]=useState({...defaults,project_id:params.get("project")??""});const [initialized,setInitialized]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(settings.data&&!initialized){const value=settings.data;setForm(current=>({...current,language:value.meeting_input_language,secondary_language:value.secondary_meeting_language,transcript_display_language:value.transcript_display_language,translation_language:value.translation_language,analysis_language_mode:value.translation_language==="none"?"original":"both",suggestion_language:value.suggestion_output_language,summary_language:value.summary_output_language,export_language:value.export_language,tts_language:value.tts_language,tts_voice:value.tts_voice,tts_rate:value.tts_rate,tts_volume:value.tts_volume,automatic_analysis_enabled:value.automatic_analysis_enabled,analysis_interval_seconds:value.periodic_analysis_seconds,suggestion_cooldown_seconds:value.suggestion_cooldown_seconds}));setInitialized(true)}},[settings.data,initialized]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setError("");try{const meeting=await post<Meeting>("/meetings",{...form,project_id:form.project_id||null,participants:form.participants.split(",").map(value=>value.trim()).filter(Boolean),repository_path:form.repository_path||null});await post(`/meetings/${meeting.id}/start`);navigate(`/meetings/${meeting.id}`)}catch(reason){setError(reason instanceof Error?reason.message:"建立失敗")}};
  const field=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>setForm(current=>({...current,[key]:value}));const options=(special?:[string,string])=><>{special&&<option value={special[0]}>{special[1]}</option>}{languages.map(([code,label])=><option value={code} key={code}>{label}</option>)}</>;
  return <div className="page"><header className="page-head"><div><p className="eyebrow">MEETING PREPARATION</p><h1>準備新會議</h1><p>獨立設定輸入、逐字稿、翻譯、分析輸出、匯出與語音語言。</p></div></header><form className="prep" onSubmit={event=>void submit(event)}><section><h2>會議內容</h2><div className="form-grid"><label>專案<select value={form.project_id} onChange={e=>field("project_id",e.target.value)}><option value="">不隸屬專案</option>{projects.data?.map(project=><option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label className="wide">標題<input required maxLength={200} value={form.title} onChange={e=>field("title",e.target.value)}/></label><label className="wide">目標<textarea required rows={3} value={form.goal} onChange={e=>field("goal",e.target.value)}/></label><label>參與者（逗號分隔）<input value={form.participants} onChange={e=>field("participants",e.target.value)}/></label><label className="wide">參考筆記<textarea rows={4} value={form.reference_notes} onChange={e=>field("reference_notes",e.target.value)}/></label></div></section>
    <section><h2>語言矩陣</h2><div className="form-grid"><label>會議輸入<select value={form.language} onChange={e=>field("language",e.target.value)}>{options(["auto","自動偵測"])}</select></label><label>次要語言<select value={form.secondary_language} onChange={e=>field("secondary_language",e.target.value)}>{options(["none","無"])}</select></label><label>逐字稿顯示<select value={form.transcript_display_language} onChange={e=>field("transcript_display_language",e.target.value)}>{options(["original","原文 + 可用翻譯"])}</select></label><label>翻譯<select value={form.translation_language} onChange={e=>{field("translation_language",e.target.value);if(e.target.value==="none")field("analysis_language_mode","original")}}>{options(["none","不翻譯"])}</select></label><label>Codex 分析內容<select value={form.analysis_language_mode} disabled={form.translation_language==="none"} onChange={e=>field("analysis_language_mode",e.target.value)}><option value="original">原文</option><option value="translated">翻譯</option><option value="both">原文與翻譯</option></select></label><label>建議輸出<select value={form.suggestion_language} onChange={e=>field("suggestion_language",e.target.value)}>{options()}</select></label><label>摘要輸出<select value={form.summary_language} onChange={e=>field("summary_language",e.target.value)}>{options()}</select></label><label>匯出<select value={form.export_language} onChange={e=>field("export_language",e.target.value)}>{options(["original","原文"])}</select></label><label>TTS<select value={form.tts_language} onChange={e=>field("tts_language",e.target.value)}>{options()}</select></label></div></section>
    <section><h2>音訊與模型</h2><div className="form-grid"><label>STT<select value={form.stt_provider_id} onChange={e=>field("stt_provider_id",e.target.value)}>{providers.data?.filter(p=>p.role==="stt").map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>TTS<select value={form.tts_provider_id} onChange={e=>field("tts_provider_id",e.target.value)}>{providers.data?.filter(p=>p.role==="tts").map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>分析引擎<select value={form.analysis_engine} onChange={e=>field("analysis_engine",e.target.value)}><option value="codex">Codex</option><option value="claude">Claude Code</option></select></label><label>Codex profile<input value={form.codex_profile} disabled={form.analysis_engine!=="codex"} onChange={e=>field("codex_profile",e.target.value)}/></label><label>分析間隔（秒）<input type="number" min="30" value={form.analysis_interval_seconds} onChange={e=>field("analysis_interval_seconds",Number(e.target.value))}/></label><label>建議冷卻（秒）<input type="number" min="0" value={form.suggestion_cooldown_seconds} onChange={e=>field("suggestion_cooldown_seconds",Number(e.target.value))}/></label></div><div className="meter"><i style={{width:`${mic.level*100}%`}}/></div><button type="button" className="button" onClick={()=>mic.active?mic.stop():void mic.start()}><Mic size={16}/>{mic.active?"停止麥克風測試":"麥克風測試"}</button>{mic.error&&<span className="field-error">{mic.error}</span>}</section>
    <section><h2>政策與隱私</h2><div className="toggle-list"><label><input type="checkbox" checked={form.automatic_analysis_enabled} onChange={e=>field("automatic_analysis_enabled",e.target.checked)}/><span>自動分析</span><small>規則觸發且通過 cooldown 才執行 Codex</small></label><label><input type="checkbox" checked={!form.human_approval_before_speech} onChange={e=>field("human_approval_before_speech",!e.target.checked)}/><span>自動朗讀 AI 建議</span><small>有新建議時立即使用所選 TTS 播放</small></label><label><input type="checkbox" checked={form.save_audio} onChange={e=>field("save_audio",e.target.checked)}/><span>保存原始音訊</span><small>預設關閉</small></label><label><input type="checkbox" checked={form.repository_context_enabled} onChange={e=>field("repository_context_enabled",e.target.checked)}/><span>啟用 repository context</span><small>必須位於後端 allowlist 且唯讀</small></label>{form.repository_context_enabled&&<label className="path-field">Repository path<input required value={form.repository_path} onChange={e=>field("repository_path",e.target.value)}/></label>}<label className="consent"><input required type="checkbox" checked={form.privacy_acknowledged} onChange={e=>field("privacy_acknowledged",e.target.checked)}/><ShieldCheck/><span>我已告知參與者麥克風音訊將在本機轉錄，並同意上述保存設定。</span></label></div></section>{error&&<div className="alert error">{error}</div>}<footer className="form-footer"><button type="button" className="button" onClick={()=>navigate("/")}>取消</button><button className="button primary"><Play size={16}/>開始會議</button></footer></form></div>;
}
