import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, BookOpen, Edit3, FolderKanban, Plus, Search, Trash2, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useDialogs } from "../components/DialogProvider";
import {
  GlossaryEntry,
  LanguageCode,
  Project,
  ProjectMemory,
  getMeetings,
  getProject,
  getProjectGlossary,
  getProjectMemory,
  getProjects,
  post,
  put,
  remove,
} from "../lib/api";

const languages: LanguageCode[] = ["zh-TW", "zh-CN", "en", "ja", "ko"];
const categories = ["architecture", "apis", "data_model", "infrastructure", "security_constraints", "performance_constraints", "business_constraints", "naming_conventions", "coding_conventions", "deployment_conventions", "known_risks", "lessons_learned", "rejected_alternatives", "glossary", "stakeholders", "project_goals", "project_non_goals"];
type MemoryForm = Pick<ProjectMemory, "category"|"title"|"content"|"source_meeting_id"|"source_decision_id"|"confidence"|"status">;
const emptyProject = { name:"", description:"", goals:"", non_goals:"", default_language:"zh-TW" as LanguageCode };
const emptyGlossary = { term:"", language:"zh-TW" as LanguageCode, preferred_spelling:"", translation:"", description:"", aliases:"", do_not_translate:false };
const emptyMemory: MemoryForm = { category:"architecture", title:"", content:"", source_meeting_id:null, source_decision_id:null, confidence:1, status:"active" };

export function Projects(){
  const dialogs=useDialogs();
  const queryClient=useQueryClient(); const projects=useQuery({queryKey:["projects"],queryFn:getProjects});
  const [query,setQuery]=useState(""); const [editing,setEditing]=useState<Project|null|undefined>();
  const [form,setForm]=useState(emptyProject); const [error,setError]=useState("");
  const open=(project?:Project)=>{setEditing(project??null);setForm(project?{name:project.name,description:project.description,goals:project.goals,non_goals:project.non_goals,default_language:project.default_language}:emptyProject);setError("")};
  const save=async(event:FormEvent)=>{event.preventDefault();setError("");try{if(editing)await put(`/projects/${editing.id}`,form);else await post("/projects",form);await queryClient.invalidateQueries({queryKey:["projects"]});setEditing(undefined)}catch(reason){setError(reason instanceof Error?reason.message:"儲存失敗")}};
  const destroy=async(project:Project)=>{if(!await dialogs.confirm({title:"刪除專案",message:`刪除專案「${project.name}」及其 glossary 與 memory？會議會保留。`,confirmLabel:"刪除",danger:true}))return;await remove(`/projects/${project.id}`);await queryClient.invalidateQueries({queryKey:["projects"]})};
  const rows=(projects.data??[]).filter(item=>`${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page"><header className="page-head"><div><p className="eyebrow">PROJECTS</p><h1>專案</h1><p>集中管理跨會議目標、術語與長期記憶。</p></div><div className="head-actions"><button className="button primary" onClick={()=>open()}><Plus size={17}/>新增專案</button></div></header>
    <div className="project-toolbar"><div className="search large"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋專案"/></div><span>{rows.length} 個專案</span></div>
    <div className="project-grid">{rows.map(project=><article className="project-card" key={project.id}><header><FolderKanban/><span>{project.default_language}</span></header><Link to={`/projects/${project.id}`}><h2>{project.name}</h2><p>{project.description||"尚未填寫專案說明"}</p></Link><dl><div><dt>目標</dt><dd>{project.goals||"未設定"}</dd></div><div><dt>更新</dt><dd>{new Date(project.updated_at).toLocaleDateString()}</dd></div></dl><footer><Link className="button" to={`/projects/${project.id}`}>開啟儀表板</Link><button className="icon-button" title="編輯專案" onClick={()=>open(project)}><Edit3 size={15}/></button><button className="icon-button danger" title="刪除專案" onClick={()=>void destroy(project)}><Trash2 size={15}/></button></footer></article>)}{!rows.length&&<div className="empty full"><FolderKanban/><strong>尚無符合的專案</strong><button className="button" onClick={()=>open()}>建立第一個專案</button></div>}</div>
    {editing!==undefined&&<div className="modal-backdrop"><form className="modal" onSubmit={event=>void save(event)}><header><h2>{editing?"編輯專案":"新增專案"}</h2><button type="button" className="icon-button" title="關閉" onClick={()=>setEditing(undefined)}><X/></button></header><div className="form-grid"><label className="wide">名稱<input required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="wide">說明<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>預設語言<select value={form.default_language} onChange={e=>setForm({...form,default_language:e.target.value as LanguageCode})}>{languages.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">目標<textarea rows={4} value={form.goals} onChange={e=>setForm({...form,goals:e.target.value})}/></label><label className="wide">非目標<textarea rows={3} value={form.non_goals} onChange={e=>setForm({...form,non_goals:e.target.value})}/></label></div>{error&&<div className="alert error">{error}</div>}<footer><button type="button" className="button" onClick={()=>setEditing(undefined)}>取消</button><button className="button primary">儲存</button></footer></form></div>}
  </div>
}

export function ProjectDashboard(){
  const dialogs=useDialogs();
  const {id=""}=useParams(); const navigate=useNavigate(); const queryClient=useQueryClient();
  const project=useQuery({queryKey:["project",id],queryFn:()=>getProject(id)}); const meetings=useQuery({queryKey:["meetings"],queryFn:getMeetings});
  const glossary=useQuery({queryKey:["project-glossary",id],queryFn:()=>getProjectGlossary(id)}); const memory=useQuery({queryKey:["project-memory",id],queryFn:()=>getProjectMemory(id)});
  const [tab,setTab]=useState<"overview"|"memory"|"glossary">("overview"); const [search,setSearch]=useState("");
  const [glossaryEdit,setGlossaryEdit]=useState<GlossaryEntry|null|undefined>(); const [glossaryForm,setGlossaryForm]=useState(emptyGlossary);
  const [memoryEdit,setMemoryEdit]=useState<ProjectMemory|null|undefined>(); const [memoryForm,setMemoryForm]=useState(emptyMemory); const [error,setError]=useState("");
  const openGlossary=(entry?:GlossaryEntry)=>{setGlossaryEdit(entry??null);setGlossaryForm(entry?{term:entry.term,language:entry.language,preferred_spelling:entry.preferred_spelling,translation:entry.translation,description:entry.description,aliases:entry.aliases.join(", "),do_not_translate:entry.do_not_translate}:emptyGlossary);setError("")};
  const saveGlossary=async(event:FormEvent)=>{event.preventDefault();setError("");const payload={...glossaryForm,aliases:glossaryForm.aliases.split(",").map(x=>x.trim()).filter(Boolean)};try{if(glossaryEdit)await put(`/project-glossary/${glossaryEdit.id}`,payload);else await post(`/projects/${id}/glossary`,payload);await queryClient.invalidateQueries({queryKey:["project-glossary",id]});await queryClient.invalidateQueries({queryKey:["project",id]});setGlossaryEdit(undefined)}catch(reason){setError(reason instanceof Error?reason.message:"儲存失敗")}};
  const openMemory=(entry?:ProjectMemory)=>{setMemoryEdit(entry??null);setMemoryForm(entry?{category:entry.category,title:entry.title,content:entry.content,source_meeting_id:entry.source_meeting_id,source_decision_id:entry.source_decision_id,confidence:entry.confidence,status:entry.status}:emptyMemory);setError("")};
  const saveMemory=async(event:FormEvent)=>{event.preventDefault();setError("");try{if(memoryEdit)await put(`/project-memory/${memoryEdit.id}`,memoryForm);else await post(`/projects/${id}/memory`,memoryForm);await queryClient.invalidateQueries({queryKey:["project-memory",id]});await queryClient.invalidateQueries({queryKey:["project",id]});setMemoryEdit(undefined)}catch(reason){setError(reason instanceof Error?reason.message:"儲存失敗")}};
  const archive=async(entry:ProjectMemory)=>{await put(`/project-memory/${entry.id}`,{...entry,status:"archived"});await queryClient.invalidateQueries({queryKey:["project-memory",id]})};
  const removeGlossary=async(entry:GlossaryEntry)=>{if(!await dialogs.confirm({title:"刪除術語",message:`刪除術語「${entry.term}」？`,confirmLabel:"刪除",danger:true}))return;await remove(`/project-glossary/${entry.id}`);await queryClient.invalidateQueries({queryKey:["project-glossary",id]});await queryClient.invalidateQueries({queryKey:["project",id]})};
  const removeMemory=async(entry:ProjectMemory)=>{if(!await dialogs.confirm({title:"永久刪除專案記憶",message:`永久刪除記憶「${entry.title}」？此操作無法復原。`,confirmLabel:"永久刪除",danger:true}))return;await remove(`/project-memory/${entry.id}`);await queryClient.invalidateQueries({queryKey:["project-memory",id]});await queryClient.invalidateQueries({queryKey:["project",id]})};
  if(project.isPending)return <div className="page"><div className="empty">載入專案</div></div>; if(!project.data)return <div className="page"><div className="alert error">專案不存在</div></div>;
  const data=project.data; const recent=(meetings.data??[]).filter(x=>x.project_id===id).slice(0,5); const memories=(memory.data??[]).filter(x=>`${x.title} ${x.content}`.toLowerCase().includes(search.toLowerCase())); const terms=(glossary.data??[]).filter(x=>`${x.term} ${x.preferred_spelling} ${x.description}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page"><header className="page-head"><div><p className="eyebrow">PROJECT · {data.default_language}</p><h1>{data.name}</h1><p>{data.description||"尚未填寫說明"}</p></div><div className="head-actions"><Link className="button primary" to={`/meetings/new?project=${id}`}><Plus size={16}/>開始會議</Link></div></header>
    <div className="detail-summary"><div><span>會議</span><strong>{data.meeting_count}</strong></div><div><span>專案記憶</span><strong>{data.memory_count}</strong></div><div><span>術語</span><strong>{data.glossary_count}</strong></div><div><span>預設語言</span><strong>{data.default_language}</strong></div></div>
    <div className="tabs">{(["overview","memory","glossary"] as const).map(x=><button className={tab===x?"active":""} onClick={()=>{setTab(x);setSearch("")}} key={x}>{x}</button>)}</div>
    {tab==="overview"&&<div className="project-overview"><section className="section-card"><h2>專案目標</h2><p className="prose">{data.goals||"尚未設定"}</p><h2>非目標</h2><p className="prose">{data.non_goals||"尚未設定"}</p></section><section className="section-card"><div className="section-title"><h2>最近會議</h2></div>{recent.map(x=><Link className="project-meeting" to={`/history/${x.id}`} key={x.id}><span>{x.title}</span><small>{x.status} · {new Date(x.created_at).toLocaleDateString()}</small></Link>)}{!recent.length&&<div className="empty small">尚無會議</div>}</section></div>}
    {tab!=="overview"&&<div className="project-toolbar"><div className="search large"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={tab==="memory"?"搜尋記憶":"搜尋術語"}/></div><button className="button primary" onClick={()=>tab==="memory"?openMemory():openGlossary()}><Plus size={16}/>{tab==="memory"?"新增記憶":"新增術語"}</button></div>}
    {tab==="memory"&&<div className="memory-list">{memories.map(entry=><article key={entry.id} className={entry.status==="archived"?"archived":""}><header><span>{entry.category.replaceAll("_"," ")}</span><small>v{entry.version} · {Math.round(entry.confidence*100)}% · {entry.status}</small></header><h3>{entry.title}</h3><p>{entry.content}</p><footer><button className="button" onClick={()=>openMemory(entry)}><Edit3 size={14}/>編輯</button>{entry.status==="active"&&<button className="icon-button" title="封存" onClick={()=>void archive(entry)}><Archive size={15}/></button>}<button className="icon-button danger" title="刪除" onClick={()=>void removeMemory(entry)}><Trash2 size={15}/></button></footer></article>)}{!memories.length&&<div className="empty"><BookOpen/><strong>沒有符合的專案記憶</strong></div>}</div>}
    {tab==="glossary"&&<div className="glossary-table"><div className="glossary-head"><span>術語</span><span>偏好拼法 / 翻譯</span><span>語言</span><span>規則</span><span/></div>{terms.map(entry=><div className="glossary-row" key={entry.id}><div><strong>{entry.term}</strong><small>{entry.aliases.join(", ")||entry.description}</small></div><span>{entry.preferred_spelling||entry.translation||"—"}</span><code>{entry.language}</code><span>{entry.do_not_translate?"禁止翻譯":"可翻譯"}</span><div><button className="icon-button" title="編輯" onClick={()=>openGlossary(entry)}><Edit3 size={14}/></button><button className="icon-button danger" title="刪除" onClick={()=>void removeGlossary(entry)}><Trash2 size={14}/></button></div></div>)}{!terms.length&&<div className="empty"><BookOpen/><strong>沒有符合的術語</strong></div>}</div>}
    {glossaryEdit!==undefined&&<div className="modal-backdrop"><form className="modal" onSubmit={event=>void saveGlossary(event)}><header><h2>{glossaryEdit?"編輯術語":"新增術語"}</h2><button type="button" className="icon-button" title="關閉" onClick={()=>setGlossaryEdit(undefined)}><X/></button></header><div className="form-grid"><label>術語<input required value={glossaryForm.term} onChange={e=>setGlossaryForm({...glossaryForm,term:e.target.value})}/></label><label>語言<select value={glossaryForm.language} onChange={e=>setGlossaryForm({...glossaryForm,language:e.target.value as LanguageCode})}>{languages.map(x=><option key={x}>{x}</option>)}</select></label><label>偏好拼法<input value={glossaryForm.preferred_spelling} onChange={e=>setGlossaryForm({...glossaryForm,preferred_spelling:e.target.value})}/></label><label>翻譯<input value={glossaryForm.translation} onChange={e=>setGlossaryForm({...glossaryForm,translation:e.target.value})}/></label><label className="wide">別名（逗號分隔）<input value={glossaryForm.aliases} onChange={e=>setGlossaryForm({...glossaryForm,aliases:e.target.value})}/></label><label className="wide">說明<textarea rows={3} value={glossaryForm.description} onChange={e=>setGlossaryForm({...glossaryForm,description:e.target.value})}/></label><label className="wide switch"><input type="checkbox" checked={glossaryForm.do_not_translate} onChange={e=>setGlossaryForm({...glossaryForm,do_not_translate:e.target.checked})}/>禁止翻譯此術語</label></div>{error&&<div className="alert error">{error}</div>}<footer><button type="button" className="button" onClick={()=>setGlossaryEdit(undefined)}>取消</button><button className="button primary">儲存</button></footer></form></div>}
    {memoryEdit!==undefined&&<div className="modal-backdrop"><form className="modal" onSubmit={event=>void saveMemory(event)}><header><h2>{memoryEdit?"編輯專案記憶":"新增專案記憶"}</h2><button type="button" className="icon-button" title="關閉" onClick={()=>setMemoryEdit(undefined)}><X/></button></header><div className="form-grid"><label>分類<select value={memoryForm.category} onChange={e=>setMemoryForm({...memoryForm,category:e.target.value})}>{categories.map(x=><option value={x} key={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>狀態<select value={memoryForm.status} onChange={e=>setMemoryForm({...memoryForm,status:e.target.value as "active"|"archived"|"superseded"})}><option value="active">active</option><option value="archived">archived</option><option value="superseded">superseded</option></select></label><label className="wide">標題<input required value={memoryForm.title} onChange={e=>setMemoryForm({...memoryForm,title:e.target.value})}/></label><label className="wide">內容<textarea required rows={8} value={memoryForm.content} onChange={e=>setMemoryForm({...memoryForm,content:e.target.value})}/></label><label className="wide">信心值 <output>{Math.round(memoryForm.confidence*100)}%</output><input type="range" min="0" max="1" step="0.05" value={memoryForm.confidence} onChange={e=>setMemoryForm({...memoryForm,confidence:Number(e.target.value)})}/></label></div>{error&&<div className="alert error">{error}</div>}<footer><button type="button" className="button" onClick={()=>setMemoryEdit(undefined)}>取消</button><button className="button primary">儲存</button></footer></form></div>}
    <button className="button project-back" onClick={()=>navigate("/projects")}>返回專案列表</button>
  </div>
}
