import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, FlaskConical, Plus, Save, Star, Trash2, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { getProviders, post, Provider, put, remove } from "../lib/api";

const blank={id:"",name:"",role:"stt",provider_type:"local_faster_whisper",base_url:"",secret_ref:"",model:"",enabled:true,timeout_seconds:60,max_retries:2,extra:"{}"};
export function Providers(){const queryClient=useQueryClient();const providers=useQuery({queryKey:["providers"],queryFn:getProviders});const [editing,setEditing]=useState<typeof blank|null>(null);const refresh=()=>void queryClient.invalidateQueries({queryKey:["providers"]});const test=useMutation({mutationFn:(id:string)=>post<{healthy:boolean;detail:string}>(`/providers/${id}/test`),onSuccess:refresh});
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!editing)return;const payload={...editing,base_url:editing.base_url||null,secret_ref:editing.secret_ref||null,model:editing.model||null,extra:JSON.parse(editing.extra)};delete (payload as Partial<typeof payload>).extra;const body={...payload,extra:JSON.parse(editing.extra)};const exists=providers.data?.some(item=>item.id===editing.id);if(exists)await put(`/providers/${editing.id}`,body);else await post("/providers",body);setEditing(null);refresh()};
  const edit=(item:Provider)=>setEditing({...blank,...item,base_url:item.base_url??"",secret_ref:item.secret_ref??"",model:item.model??"",extra:JSON.stringify(item.extra,null,2)});
  return <div className="page"><header className="page-head"><div><p className="eyebrow">MODEL REGISTRY</p><h1>模型與端點</h1><p>秘密只接受環境變數名稱，API 永不回傳原始值。</p></div><button className="button primary" onClick={()=>setEditing(blank)}><Plus size={16}/>新增 Provider</button></header><div className="provider-grid">{providers.data?.map(item=><article className="provider" key={item.id}><div className="provider-head"><span className="role">{item.role}</span>{item.is_default&&<span className="default"><Star size={12}/>DEFAULT</span>}</div><h2>{item.name}</h2><code>{item.provider_type} · {item.model||"no model"}</code><dl><div><dt>Health</dt><dd className={item.health_status==="healthy"?"text-good":""}>{item.health_status}</dd></div><div><dt>Latency</dt><dd>{item.last_latency_ms?`${item.last_latency_ms} ms`:"—"}</dd></div><div><dt>Secret ref</dt><dd>{item.secret_ref||"none"}</dd></div></dl><div className="card-actions"><button className="icon-button" title="測試連線" onClick={()=>test.mutate(item.id)}><FlaskConical size={16}/></button><button className="button" onClick={()=>edit(item)}>編輯</button><button className="icon-button" title="設為預設" onClick={()=>void post(`/providers/${item.id}/set-default`).then(refresh)}><Star size={16}/></button><button className="icon-button danger" title="刪除" onClick={()=>confirm(`刪除 ${item.name}？`)&&void remove(`/providers/${item.id}`).then(refresh)}><Trash2 size={16}/></button></div></article>)}</div>{test.data&&<div className={`toast ${test.data.healthy?"success":"error"}`}><CheckCircle2 size={16}/>{test.data.detail}</div>}
  {editing&&<div className="modal-backdrop"><form className="modal" onSubmit={event=>void submit(event)}><header><h2>Provider 設定</h2><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X/></button></header><div className="form-grid"><label>ID<input value={editing.id} required pattern="[a-z0-9][a-z0-9_-]{2,63}" onChange={e=>setEditing({...editing,id:e.target.value})}/></label><label>名稱<input value={editing.name} required onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>角色<select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}><option>reasoning</option><option>stt</option><option>tts</option><option>embedding</option><option>reranker</option></select></label><label>Provider type<select value={editing.provider_type} onChange={e=>setEditing({...editing,provider_type:e.target.value})}><option>codex_cli</option><option>local_faster_whisper</option><option>openai_compatible_stt</option><option>browser_speech_synthesis</option><option>openai_compatible_tts</option><option>openai_compatible_embedding</option><option>custom_http</option></select></label><label className="wide">Base URL<input type="url" value={editing.base_url} onChange={e=>setEditing({...editing,base_url:e.target.value})}/></label><label>Model<input value={editing.model} onChange={e=>setEditing({...editing,model:e.target.value})}/></label><label>Secret env 名稱<input value={editing.secret_ref} onChange={e=>setEditing({...editing,secret_ref:e.target.value})}/></label><label>Timeout<input type="number" min="1" max="600" value={editing.timeout_seconds} onChange={e=>setEditing({...editing,timeout_seconds:Number(e.target.value)})}/></label><label>Retries<input type="number" min="0" max="5" value={editing.max_retries} onChange={e=>setEditing({...editing,max_retries:Number(e.target.value)})}/></label><label className="wide">Advanced JSON<textarea rows={6} value={editing.extra} onChange={e=>setEditing({...editing,extra:e.target.value})}/></label></div><footer><button type="button" className="button" onClick={()=>setEditing(null)}>取消</button><button className="button primary"><Save size={16}/>儲存</button></footer></form></div>}</div>}
