import { useMutation, useQuery } from "@tanstack/react-query";
import { Check, ChevronLeft, ChevronRight, CircleAlert, LoaderCircle, Mic, Play, RefreshCw, Volume2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getSystem, post } from "../lib/api";
import { useMicrophone } from "../hooks/useMicrophone";

const steps=["系統檢查","Codex 驗證","推理設定","STT 測試","TTS 測試","麥克風","完成"];
export function Setup(){const [step,setStep]=useState(0);const navigate=useNavigate();const system=useQuery({queryKey:["system"],queryFn:getSystem});const mic=useMicrophone();const codexTest=useMutation({mutationFn:()=>post<{healthy:boolean;error:string}>("/codex/test")});
  const checks=useMemo(()=>system.data?[ ["Python 3.10+",Number(system.data.python_version.split(".")[0])>=3], ["Database",system.data.database.healthy], ["FFmpeg",system.data.ffmpeg_available], ["Codex CLI",system.data.codex.installed], ["NVIDIA / CUDA",system.data.gpu.available], ["Docker",system.data.docker_available] ]:[],[system.data]);
  const speak=()=>{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance("Meeting Copilot 語音測試正常");utterance.lang="zh-TW";speechSynthesis.speak(utterance)};
  return <div className="page"><header className="page-head"><div><p className="eyebrow">INITIAL SETUP</p><h1>設定精靈</h1><p>逐項驗證本機依賴與會議裝置。</p></div></header><div className="wizard"><ol>{steps.map((label,index)=><li className={index===step?"active":index<step?"done":""} key={label}><span>{index<step?<Check size={14}/>:index+1}</span>{label}</li>)}</ol><section className="wizard-body">
    {step===0&&<><h2>系統檢查</h2><p>必要元件會直接由後端檢測；GPU 缺失時 STT 可切換 CPU 備援。</p><div className="check-list">{system.isPending?<LoaderCircle className="spin"/>:checks.map(([label,ok])=><div key={String(label)}><span className={`check-icon ${ok?"pass":"fail"}`}>{ok?<Check size={16}/>:<CircleAlert size={16}/>}</span><strong>{label}</strong><span>{ok?"通過":"需要處理"}</span></div>)}</div><button className="button" onClick={()=>void system.refetch()}><RefreshCw size={16}/>重新檢查</button></>}
    {step===1&&<><h2>Codex 驗證</h2><p>使用主機既有 Codex 登入，不讀取或顯示 credential file。</p><div className="fact-grid"><div><span>CLI</span><strong>{system.data?.codex.version??"未安裝"}</strong></div><div><span>狀態</span><strong>{system.data?.codex.authenticated?"已登入":"待登入"}</strong></div></div><div className="button-row"><button className="button primary" onClick={()=>codexTest.mutate()} disabled={codexTest.isPending}>測試 Codex</button><button className="button" onClick={()=>void post("/codex/login/start")}>啟動裝置登入</button><button className="button" onClick={()=>void post("/codex/login/cancel")}>取消登入</button><button className="button" onClick={()=>void post("/codex/logout").then(()=>system.refetch())}>登出</button><button className="button" onClick={()=>alert(JSON.stringify(system.data?.codex??{},null,2))}>檢視遮罩設定</button><button className="icon-button" title="重新整理" onClick={()=>void system.refetch()}><RefreshCw/></button></div>{codexTest.data&&<div className={`alert ${codexTest.data.healthy?"success":"error"}`}>{codexTest.data.healthy?"Codex structured task 完成":codexTest.data.error}</div>}</>}
    {step===2&&<><h2>推理設定</h2><p>預設為唯讀 sandbox、無核准、無 repository context。模型與 profile 由 Providers 頁面管理。</p><div className="policy"><div><span>Sandbox</span><strong>read-only</strong></div><div><span>Network</span><strong>disabled</strong></div><div><span>Repository</span><strong>disabled</strong></div><div><span>Timeout</span><strong>180 sec</strong></div></div></>}
    {step===3&&<><h2>STT 設定</h2><p>預設載入 <code>large-v3-turbo</code>、CUDA float16、VAD；CUDA 初始化失敗時切換 medium CPU int8。</p><div className="fact-grid"><div><span>GPU</span><strong>{system.data?.gpu.gpus[0]?.name??"CPU fallback"}</strong></div><div><span>FFmpeg</span><strong>{system.data?.ffmpeg_available?"Ready":"Missing"}</strong></div></div><button className="button" onClick={()=>navigate("/diagnostics")}>開啟 benchmark 與診斷</button></>}
    {step===4&&<><h2>TTS 測試</h2><p>第一階段使用瀏覽器 SpeechSynthesis，只有人員點擊後才播放。</p><button className="button primary" onClick={speak}><Volume2 size={16}/>播放測試語音</button><button className="button" onClick={()=>speechSynthesis.cancel()}>停止播放</button></>}
    {step===5&&<><h2>麥克風測試</h2><p>瀏覽器取得權限後顯示即時音量；測試音訊不會上傳或保存。</p><div className="meter"><i style={{width:`${mic.level*100}%`}}/></div>{mic.error&&<div className="alert error">{mic.error}</div>}<button className={`button ${mic.active?"":"primary"}`} onClick={()=>mic.active?mic.stop():void mic.start()}><Mic size={16}/>{mic.active?"停止測試":"允許並測試"}</button></>}
    {step===6&&<><h2>本機系統已設定</h2><p>可隨時回到此頁重新檢測依賴。Codex 與外部端點仍維持機器層級設定。</p><button className="button primary" onClick={()=>{localStorage.setItem("meeting-copilot-setup","complete");navigate("/")}}>開啟會議工作台</button></>}
    <footer><button className="button" disabled={step===0} onClick={()=>setStep(value=>value-1)}><ChevronLeft size={16}/>上一步</button>{step<6&&<button className="button primary" onClick={()=>setStep(value=>value+1)}>下一步<ChevronRight size={16}/></button>}</footer></section></div></div>}
