import { ReactNode, createContext, useContext, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { LanguageCode, getSettings } from "./lib/api";

const messages = {
  "zh-TW": {dashboard:"總覽",setup:"設定精靈",providers:"模型與端點",cliAuth:"CLI 登入",projects:"專案",decisions:"決策",actions:"行動項目",knowledge:"知識庫",meetings:"會議",history:"歷史",diagnostics:"診斷",settings:"設定",access:"存取控制",local:"本機優先",save:"儲存設定",loading:"載入中",systemSettings:"系統設定",dashboardTitle:"會議工作台",dashboardSubtitle:"本機處理語音，推理引擎僅在需要時參與。",refresh:"重新整理",startMeeting:"開始新會議",backendUnavailable:"無法連線後端",checking:"檢查中",healthy:"正常",signInRequired:"待登入",bothEnginesSignedIn:"雙引擎已登入",codexSignedIn:"Codex 已登入",claudeSignedIn:"Claude 已登入",cudaAvailable:"CUDA 可用",cpuFallback:"CPU 備援",gpuUsage:"GPU 使用率",gpuMemory:"GPU 記憶體",gpuNotDetected:"未偵測到 NVIDIA GPU",gpuMemoryNote:"全卡用量（含其他程序）· ECC 保留後容量",sttUsesCpu:"STT 將使用 CPU",databaseLatency:"資料庫延遲",inferenceQueue:"推理佇列",noInferenceJobs:"無等待中的推理工作",recentMeetings:"最近會議",viewAll:"查看全部",noMeetings:"尚無會議紀錄",noMeetingsHint:"開始第一場會議後，逐字稿與決策會出現在這裡。",createMeeting:"建立會議",runtime:"執行環境",operatingSystem:"作業系統",notDetected:"未偵測",available:"可用",notInstalled:"未安裝",diskSpace:"磁碟空間",gbAvailable:"GB 可用",settingsSubtitle:"語言、分析觸發與播放政策由後端驗證並儲存。",languageMatrix:"語言矩陣",meetingInput:"會議輸入",secondaryInput:"次要輸入",transcriptDisplay:"逐字稿顯示",translation:"翻譯",suggestions:"建議",summary:"摘要",export:"匯出",autoDetect:"自動偵測",none:"無",original:"原文",noTranslation:"不翻譯",triggerPolicy:"分析觸發政策",periodicSeconds:"週期分析（秒）",minimumCharacters:"最少新字元",suggestionCooldown:"建議冷卻",contextMinutes:"內容範圍（分鐘）",contextCharacters:"內容字元上限",enableAutoAnalysis:"預設啟用自動分析",speechPlayback:"語音播放",voiceName:"語音名稱",browserDefault:"留白使用瀏覽器預設",rate:"速率",volume:"音量",testVoice:"測試語音",settingsSaved:"設定已儲存",settingsApplied:"新的語言、分析與播放政策已套用。"},
  "zh-CN": {dashboard:"总览",setup:"设置向导",providers:"模型与端点",cliAuth:"CLI 登录",projects:"项目",decisions:"决策",actions:"行动项目",knowledge:"知识库",meetings:"会议",history:"历史",diagnostics:"诊断",settings:"设置",access:"访问控制",local:"本地优先",save:"保存设置",loading:"加载中",systemSettings:"系统设置",dashboardTitle:"会议工作台",dashboardSubtitle:"语音在本地处理，推理引擎仅在需要时参与。",refresh:"刷新",startMeeting:"开始新会议",backendUnavailable:"无法连接后端",checking:"检查中",healthy:"正常",signInRequired:"待登录",bothEnginesSignedIn:"双引擎已登录",codexSignedIn:"Codex 已登录",claudeSignedIn:"Claude 已登录",cudaAvailable:"CUDA 可用",cpuFallback:"CPU 备用",gpuUsage:"GPU 使用率",gpuMemory:"GPU 显存",gpuNotDetected:"未检测到 NVIDIA GPU",gpuMemoryNote:"整卡用量（含其他进程）· ECC 保留后容量",sttUsesCpu:"STT 将使用 CPU",databaseLatency:"数据库延迟",inferenceQueue:"推理队列",noInferenceJobs:"没有等待中的推理任务",recentMeetings:"最近会议",viewAll:"查看全部",noMeetings:"暂无会议记录",noMeetingsHint:"开始第一场会议后，转录与决策会显示在这里。",createMeeting:"创建会议",runtime:"运行环境",operatingSystem:"操作系统",notDetected:"未检测",available:"可用",notInstalled:"未安装",diskSpace:"磁盘空间",gbAvailable:"GB 可用",settingsSubtitle:"语言、分析触发与播放策略由后端验证并保存。",languageMatrix:"语言矩阵",meetingInput:"会议输入",secondaryInput:"次要输入",transcriptDisplay:"转录显示",translation:"翻译",suggestions:"建议",summary:"摘要",export:"导出",autoDetect:"自动检测",none:"无",original:"原文",noTranslation:"不翻译",triggerPolicy:"分析触发策略",periodicSeconds:"周期分析（秒）",minimumCharacters:"最少新字符",suggestionCooldown:"建议冷却",contextMinutes:"上下文（分钟）",contextCharacters:"上下文字符上限",enableAutoAnalysis:"默认启用自动分析",speechPlayback:"语音播放",voiceName:"语音名称",browserDefault:"留空使用浏览器默认值",rate:"速率",volume:"音量",testVoice:"测试语音",settingsSaved:"设置已保存",settingsApplied:"新的语言、分析与播放策略已应用。"},
  en: {dashboard:"Dashboard",setup:"Setup",providers:"Models & endpoints",cliAuth:"CLI sign-in",projects:"Projects",decisions:"Decisions",actions:"Action items",knowledge:"Knowledge",meetings:"Meetings",history:"History",diagnostics:"Diagnostics",settings:"Settings",access:"Access control",local:"Local first",save:"Save settings",loading:"Loading",systemSettings:"System settings",dashboardTitle:"Meeting workspace",dashboardSubtitle:"Speech stays local; the reasoning engine participates only when needed.",refresh:"Refresh",startMeeting:"Start meeting",backendUnavailable:"Cannot connect to backend",checking:"Checking",healthy:"Healthy",signInRequired:"Sign-in required",bothEnginesSignedIn:"Both engines signed in",codexSignedIn:"Codex signed in",claudeSignedIn:"Claude signed in",cudaAvailable:"CUDA available",cpuFallback:"CPU fallback",gpuUsage:"GPU utilization",gpuMemory:"GPU memory",gpuNotDetected:"No NVIDIA GPU detected",gpuMemoryNote:"Whole-card usage, including other processes; capacity after ECC reserve",sttUsesCpu:"STT will use CPU",databaseLatency:"Database latency",inferenceQueue:"Reasoning queue",noInferenceJobs:"No reasoning jobs waiting",recentMeetings:"Recent meetings",viewAll:"View all",noMeetings:"No meeting records",noMeetingsHint:"Transcripts and decisions will appear here after your first meeting.",createMeeting:"Create meeting",runtime:"Runtime",operatingSystem:"Operating system",notDetected:"Not detected",available:"Available",notInstalled:"Not installed",diskSpace:"Disk space",gbAvailable:"GB available",settingsSubtitle:"Language, analysis triggers, and playback policies are validated and stored by the backend.",languageMatrix:"Language matrix",meetingInput:"Meeting input",secondaryInput:"Secondary input",transcriptDisplay:"Transcript display",translation:"Translation",suggestions:"Suggestions",summary:"Summary",export:"Export",autoDetect:"Auto detect",none:"None",original:"Original",noTranslation:"No translation",triggerPolicy:"Analysis trigger policy",periodicSeconds:"Periodic analysis (seconds)",minimumCharacters:"Minimum new characters",suggestionCooldown:"Suggestion cooldown",contextMinutes:"Context (minutes)",contextCharacters:"Context character limit",enableAutoAnalysis:"Enable automatic analysis by default",speechPlayback:"Speech playback",voiceName:"Voice name",browserDefault:"Leave blank for browser default",rate:"Rate",volume:"Volume",testVoice:"Test voice",settingsSaved:"Settings saved",settingsApplied:"The new language, analysis, and playback policies are active."},
  ja: {dashboard:"概要",setup:"セットアップ",providers:"モデルと接続先",cliAuth:"CLI サインイン",projects:"プロジェクト",decisions:"意思決定",actions:"アクション",knowledge:"ナレッジ",meetings:"会議",history:"履歴",diagnostics:"診断",settings:"設定",access:"アクセス制御",local:"ローカル優先",save:"設定を保存",loading:"読み込み中",systemSettings:"システム設定",dashboardTitle:"会議ワークスペース",dashboardSubtitle:"音声はローカルで処理し、推論エンジンは必要な場合のみ使用します。",refresh:"更新",startMeeting:"新しい会議を開始",backendUnavailable:"バックエンドに接続できません",checking:"確認中",healthy:"正常",signInRequired:"サインイン待ち",bothEnginesSignedIn:"両エンジンにサインイン済み",codexSignedIn:"Codex サインイン済み",claudeSignedIn:"Claude サインイン済み",cudaAvailable:"CUDA 利用可能",cpuFallback:"CPU フォールバック",gpuUsage:"GPU 使用率",gpuMemory:"GPU メモリ",gpuNotDetected:"NVIDIA GPU が見つかりません",gpuMemoryNote:"他のプロセスを含むカード全体の使用量・ECC 予約後の容量",sttUsesCpu:"STT は CPU を使用します",databaseLatency:"データベース遅延",inferenceQueue:"推論キュー",noInferenceJobs:"待機中の推論ジョブはありません",recentMeetings:"最近の会議",viewAll:"すべて表示",noMeetings:"会議記録はありません",noMeetingsHint:"最初の会議後、文字起こしと決定事項がここに表示されます。",createMeeting:"会議を作成",runtime:"実行環境",operatingSystem:"オペレーティングシステム",notDetected:"未検出",available:"利用可能",notInstalled:"未インストール",diskSpace:"ディスク容量",gbAvailable:"GB 利用可能",settingsSubtitle:"言語、分析トリガー、再生ポリシーはバックエンドで検証・保存されます。",languageMatrix:"言語マトリクス",meetingInput:"会議入力",secondaryInput:"第2入力",transcriptDisplay:"文字起こし表示",translation:"翻訳",suggestions:"提案",summary:"要約",export:"エクスポート",autoDetect:"自動検出",none:"なし",original:"原文",noTranslation:"翻訳しない",triggerPolicy:"分析トリガーポリシー",periodicSeconds:"定期分析（秒）",minimumCharacters:"最小新規文字数",suggestionCooldown:"提案クールダウン",contextMinutes:"コンテキスト（分）",contextCharacters:"コンテキスト文字数上限",enableAutoAnalysis:"自動分析を既定で有効化",speechPlayback:"音声再生",voiceName:"音声名",browserDefault:"空欄でブラウザー既定値",rate:"速度",volume:"音量",testVoice:"音声テスト",settingsSaved:"設定を保存しました",settingsApplied:"新しい言語、分析、再生ポリシーを適用しました。"},
  ko: {dashboard:"대시보드",setup:"설정 마법사",providers:"모델 및 엔드포인트",cliAuth:"CLI 로그인",projects:"프로젝트",decisions:"결정",actions:"작업 항목",knowledge:"지식",meetings:"회의",history:"기록",diagnostics:"진단",settings:"설정",access:"접근 제어",local:"로컬 우선",save:"설정 저장",loading:"불러오는 중",systemSettings:"시스템 설정",dashboardTitle:"회의 작업 공간",dashboardSubtitle:"음성은 로컬에서 처리하며 추론 엔진은 필요할 때만 참여합니다.",refresh:"새로 고침",startMeeting:"새 회의 시작",backendUnavailable:"백엔드에 연결할 수 없음",checking:"확인 중",healthy:"정상",signInRequired:"로그인 필요",bothEnginesSignedIn:"두 엔진 로그인됨",codexSignedIn:"Codex 로그인됨",claudeSignedIn:"Claude 로그인됨",cudaAvailable:"CUDA 사용 가능",cpuFallback:"CPU 대체",gpuUsage:"GPU 사용률",gpuMemory:"GPU 메모리",gpuNotDetected:"NVIDIA GPU를 찾지 못함",gpuMemoryNote:"다른 프로세스를 포함한 전체 카드 사용량 · ECC 예약 후 용량",sttUsesCpu:"STT가 CPU를 사용합니다",databaseLatency:"데이터베이스 지연",inferenceQueue:"추론 대기열",noInferenceJobs:"대기 중인 추론 작업 없음",recentMeetings:"최근 회의",viewAll:"모두 보기",noMeetings:"회의 기록 없음",noMeetingsHint:"첫 회의 후 전사와 결정 사항이 여기에 표시됩니다.",createMeeting:"회의 만들기",runtime:"실행 환경",operatingSystem:"운영 체제",notDetected:"감지되지 않음",available:"사용 가능",notInstalled:"설치되지 않음",diskSpace:"디스크 공간",gbAvailable:"GB 사용 가능",settingsSubtitle:"언어, 분석 트리거 및 재생 정책은 백엔드에서 검증하고 저장합니다.",languageMatrix:"언어 매트릭스",meetingInput:"회의 입력",secondaryInput:"보조 입력",transcriptDisplay:"전사 표시",translation:"번역",suggestions:"제안",summary:"요약",export:"내보내기",autoDetect:"자동 감지",none:"없음",original:"원문",noTranslation:"번역 안 함",triggerPolicy:"분석 트리거 정책",periodicSeconds:"주기 분석(초)",minimumCharacters:"최소 새 문자 수",suggestionCooldown:"제안 대기 시간",contextMinutes:"컨텍스트(분)",contextCharacters:"컨텍스트 문자 제한",enableAutoAnalysis:"기본 자동 분석 사용",speechPlayback:"음성 재생",voiceName:"음성 이름",browserDefault:"비워 두면 브라우저 기본값",rate:"속도",volume:"볼륨",testVoice:"음성 테스트",settingsSaved:"설정 저장됨",settingsApplied:"새 언어, 분석 및 재생 정책이 적용되었습니다."},
} as const;

type MessageKey = keyof typeof messages.en;
type I18nValue = {language:LanguageCode;t:(key:MessageKey)=>string};
const I18nContext=createContext<I18nValue>({language:"zh-TW",t:key=>messages["zh-TW"][key]});

export function I18nProvider({children}:{children:ReactNode}){
  const settings=useQuery({queryKey:["settings"],queryFn:getSettings,staleTime:30_000});
  const language=settings.data?.ui_language??"zh-TW";
  useEffect(()=>{document.documentElement.lang=language},[language]);
  return <I18nContext.Provider value={{language,t:key=>messages[language][key]}}>{children}</I18nContext.Provider>;
}

export const useI18n=()=>useContext(I18nContext);
