import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { App } from "./App";
import { ErrorBoundary } from "./components/ErrorBoundary";
import { DialogProvider } from "./components/DialogProvider";
import { I18nProvider } from "./i18n";
import "./styles.css";
import "./extras.css";
import "./live.css";
import "./projects.css";
import "./knowledge.css";
import "./languages.css";
import "./auth.css";
import "./dialogs.css";
import "./responsive.css";

const queryClient = new QueryClient({ defaultOptions: { queries: { retry: 1, staleTime: 5_000 } } });
createRoot(document.getElementById("root")!).render(<StrictMode><ErrorBoundary><QueryClientProvider client={queryClient}><I18nProvider><DialogProvider><BrowserRouter><App/></BrowserRouter></DialogProvider></I18nProvider></QueryClientProvider></ErrorBoundary></StrictMode>);
