import { LanguageCode } from "./lib/api";

type Translation = readonly [string, string, string, string, string];

export const phrases = {
  "Primary navigation": [
    "主要導覽",
    "主要导航",
    "Primary navigation",
    "メインナビゲーション",
    "기본 탐색",
  ],
  "{count} overdue action items": [
    "{count} 項行動項目已逾期",
    "{count} 个行动项目已逾期",
    "{count} overdue action items",
    "期限切れのアクション項目 {count} 件",
    "기한이 지난 작업 항목 {count}개",
  ],
  Close: ["關閉", "关闭", "Close", "閉じる", "닫기"],
  Cancel: ["取消", "取消", "Cancel", "キャンセル", "취소"],
  Confirm: ["確認", "确认", "Confirm", "確認", "확인"],
  Content: ["內容", "内容", "Content", "内容", "내용"],
  Caution: ["注意", "注意", "Caution", "注意", "주의"],
  "This network address requires administrator sign-in.": [
    "此網路位址需要管理員登入。",
    "此网络地址需要管理员登录。",
    "This network address requires administrator sign-in.",
    "このネットワークアドレスには管理者のサインインが必要です。",
    "이 네트워크 주소에는 관리자 로그인이 필요합니다.",
  ],
  Username: ["使用者名稱", "用户名", "Username", "ユーザー名", "사용자 이름"],
  Password: ["密碼", "密码", "Password", "パスワード", "비밀번호"],
  "Sign in": ["登入", "登录", "Sign in", "サインイン", "로그인"],
  "Checking access": [
    "檢查存取權限",
    "检查访问权限",
    "Checking access",
    "アクセス権を確認中",
    "접근 권한 확인 중",
  ],
  "Unable to verify access": [
    "無法驗證存取權限",
    "无法验证访问权限",
    "Unable to verify access",
    "アクセス権を確認できません",
    "접근 권한을 확인할 수 없음",
  ],
  "Administrator is not configured": [
    "尚未設定管理員",
    "尚未设置管理员",
    "Administrator is not configured",
    "管理者が未設定です",
    "관리자가 설정되지 않음",
  ],
  "Open https://localhost/access on the host to create an administrator password, then return here to sign in.":
    [
      "請先從主機開啟 https://localhost/access 建立管理員密碼，再回到此位址登入。",
      "请先在主机打开 https://localhost/access 创建管理员密码，然后返回此处登录。",
      "Open https://localhost/access on the host to create an administrator password, then return here to sign in.",
      "ホストで https://localhost/access を開いて管理者パスワードを作成し、ここに戻ってサインインしてください。",
      "호스트에서 https://localhost/access를 열어 관리자 비밀번호를 만든 후 여기로 돌아와 로그인하세요.",
    ],
  "Page could not be displayed.": [
    "頁面無法顯示。",
    "页面无法显示。",
    "Page could not be displayed.",
    "ページを表示できません。",
    "페이지를 표시할 수 없습니다.",
  ],
  "Reload the page; meetings and transcripts remain stored in the backend.": [
    "請重新載入；會議與逐字稿仍保存在後端。",
    "请重新加载；会议和转录仍保存在后端。",
    "Reload the page; meetings and transcripts remain stored in the backend.",
    "ページを再読み込みしてください。会議と文字起こしはバックエンドに保存されています。",
    "페이지를 새로 고치세요. 회의와 전사는 백엔드에 보관되어 있습니다.",
  ],
  Reload: ["重新載入", "重新加载", "Reload", "再読み込み", "새로 고침"],
  "Access control": [
    "存取控制",
    "访问控制",
    "Access control",
    "アクセス制御",
    "접근 제어",
  ],
  "LAN access uses an Argon2 administrator password, HttpOnly session, and CSRF validation.":
    [
      "LAN 位址使用 Argon2 管理員密碼、HttpOnly session 與 CSRF 驗證。",
      "LAN 地址使用 Argon2 管理员密码、HttpOnly 会话和 CSRF 验证。",
      "LAN access uses an Argon2 administrator password, HttpOnly session, and CSRF validation.",
      "LAN アクセスは Argon2 管理者パスワード、HttpOnly セッション、CSRF 検証を使用します。",
      "LAN 접근은 Argon2 관리자 비밀번호, HttpOnly 세션 및 CSRF 검증을 사용합니다.",
    ],
  "Passwords do not match": [
    "兩次密碼不一致",
    "两次密码不一致",
    "Passwords do not match",
    "パスワードが一致しません",
    "비밀번호가 일치하지 않습니다",
  ],
  "Administrator created; devices on this domain must now sign in.": [
    "管理員已建立；同網域裝置現在必須登入。",
    "管理员已创建；同域设备现在必须登录。",
    "Administrator created; devices on this domain must now sign in.",
    "管理者を作成しました。同じドメインの端末はサインインが必要です。",
    "관리자가 생성되었습니다. 같은 도메인의 기기는 이제 로그인해야 합니다.",
  ],
  "Setup failed": [
    "設定失敗",
    "设置失败",
    "Setup failed",
    "設定に失敗しました",
    "설정 실패",
  ],
  "Administrator configured": [
    "管理員已設定",
    "管理员已设置",
    "Administrator configured",
    "管理者設定済み",
    "관리자 설정됨",
  ],
  "Localhost currently requires no sign-in; remote addresses show the sign-in screen.":
    [
      "目前 localhost 不需登入；遠端位址會顯示登入畫面。",
      "当前 localhost 无需登录；远程地址会显示登录页面。",
      "Localhost currently requires no sign-in; remote addresses show the sign-in screen.",
      "現在 localhost はサインイン不要です。リモートアドレスではサインイン画面が表示されます。",
      "현재 localhost는 로그인이 필요 없으며 원격 주소에는 로그인 화면이 표시됩니다.",
    ],
  "Sign out of this session": [
    "登出此工作階段",
    "退出此会话",
    "Sign out of this session",
    "このセッションからサインアウト",
    "이 세션에서 로그아웃",
  ],
  "Create administrator": [
    "建立管理員",
    "创建管理员",
    "Create administrator",
    "管理者を作成",
    "관리자 만들기",
  ],
  "This action is available only from localhost. The password is stored only as an Argon2 hash.":
    [
      "此操作只能從 localhost 執行。密碼只會以 Argon2 hash 儲存。",
      "此操作只能从 localhost 执行。密码仅以 Argon2 哈希存储。",
      "This action is available only from localhost. The password is stored only as an Argon2 hash.",
      "この操作は localhost からのみ実行できます。パスワードは Argon2 ハッシュとしてのみ保存されます。",
      "이 작업은 localhost에서만 실행할 수 있습니다. 비밀번호는 Argon2 해시로만 저장됩니다.",
    ],
  "Confirm password": [
    "確認密碼",
    "确认密码",
    "Confirm password",
    "パスワード確認",
    "비밀번호 확인",
  ],
  "Enable remote sign-in": [
    "啟用遠端登入",
    "启用远程登录",
    "Enable remote sign-in",
    "リモートサインインを有効化",
    "원격 로그인 활성화",
  ],
  "System diagnostics": [
    "系統診斷",
    "系统诊断",
    "System diagnostics",
    "システム診断",
    "시스템 진단",
  ],
  "All events and errors are secret-redacted before output.": [
    "所有事件與錯誤在輸出前皆經過秘密遮罩。",
    "所有事件和错误在输出前都会隐藏机密信息。",
    "All events and errors are secret-redacted before output.",
    "すべてのイベントとエラーは出力前に機密情報がマスクされます。",
    "모든 이벤트와 오류는 출력 전에 비밀 정보가 마스킹됩니다.",
  ],
  "Diagnostic bundle": [
    "診斷包",
    "诊断包",
    "Diagnostic bundle",
    "診断バンドル",
    "진단 번들",
  ],
  Test: ["測試", "测试", "Test", "テスト", "테스트"],
  "Test actions": [
    "測試動作",
    "测试操作",
    "Test actions",
    "テスト操作",
    "테스트 작업",
  ],
  "Codex test result": [
    "Codex 測試結果",
    "Codex 测试结果",
    "Codex test result",
    "Codex テスト結果",
    "Codex 테스트 결과",
  ],
  "Run fixed Codex JSON task": [
    "執行固定 Codex JSON 工作",
    "运行固定 Codex JSON 任务",
    "Run fixed Codex JSON task",
    "固定 Codex JSON タスクを実行",
    "고정 Codex JSON 작업 실행",
  ],
  "Play test speech": [
    "播放測試語音",
    "播放测试语音",
    "Play test speech",
    "テスト音声を再生",
    "테스트 음성 재생",
  ],
  "Migration validation result": [
    "Migration 驗證結果",
    "Migration 验证结果",
    "Migration validation result",
    "マイグレーション検証結果",
    "마이그레이션 검증 결과",
  ],
  "Validate migrations": [
    "驗證 migrations",
    "验证 migrations",
    "Validate migrations",
    "マイグレーションを検証",
    "마이그레이션 검증",
  ],
  "Latest 100 events": [
    "最近 100 筆事件",
    "最近 100 条事件",
    "Latest 100 events",
    "最新 100 件のイベント",
    "최근 이벤트 100개",
  ],
  "Models and endpoints": [
    "模型與端點",
    "模型与端点",
    "Models and endpoints",
    "モデルとエンドポイント",
    "모델 및 엔드포인트",
  ],
  "Secrets accept only injected environment variable names. Advanced JSON forbids secret, token, and credential fields.":
    [
      "秘密只接受已注入的環境變數名稱；Advanced JSON 禁止 secret、token 與 credential 欄位。",
      "机密仅接受已注入的环境变量名称；Advanced JSON 禁止 secret、token 和 credential 字段。",
      "Secrets accept only injected environment variable names. Advanced JSON forbids secret, token, and credential fields.",
      "シークレットには注入済み環境変数名のみ指定できます。Advanced JSON では secret、token、credential フィールドは禁止です。",
      "비밀 값은 주입된 환경 변수 이름만 허용합니다. Advanced JSON에는 secret, token 및 credential 필드를 사용할 수 없습니다.",
    ],
  "Add provider": [
    "新增 Provider",
    "新增 Provider",
    "Add provider",
    "Provider を追加",
    "Provider 추가",
  ],
  "Test connection": [
    "測試連線",
    "测试连接",
    "Test connection",
    "接続テスト",
    "연결 테스트",
  ],
  Edit: ["編輯", "编辑", "Edit", "編集", "편집"],
  Disable: ["停用", "停用", "Disable", "無効化", "비활성화"],
  Enable: ["啟用", "启用", "Enable", "有効化", "활성화"],
  "Set as default": [
    "設為預設",
    "设为默认",
    "Set as default",
    "既定に設定",
    "기본값으로 설정",
  ],
  "Delete provider": [
    "刪除 Provider",
    "删除 Provider",
    "Delete provider",
    "Provider を削除",
    "Provider 삭제",
  ],
  "Delete “{name}”? New jobs using this provider will no longer start.": [
    "刪除「{name}」？使用此 Provider 的新工作將無法啟動。",
    "删除“{name}”？使用此 Provider 的新任务将无法启动。",
    "Delete “{name}”? New jobs using this provider will no longer start.",
    "「{name}」を削除しますか？この Provider を使用する新しいジョブは開始できなくなります。",
    "“{name}”을 삭제할까요? 이 Provider를 사용하는 새 작업은 시작되지 않습니다.",
  ],
  "Provider settings": [
    "Provider 設定",
    "Provider 设置",
    "Provider settings",
    "Provider 設定",
    "Provider 설정",
  ],
  Name: ["名稱", "名称", "Name", "名前", "이름"],
  Role: ["角色", "角色", "Role", "ロール", "역할"],
  "Secret environment variable": [
    "Secret env 名稱",
    "Secret 环境变量名称",
    "Secret environment variable",
    "Secret 環境変数名",
    "Secret 환경 변수 이름",
  ],
  Save: ["儲存", "保存", "Save", "保存", "저장"],
  "CLI sign-in": [
    "CLI 登入",
    "CLI 登录",
    "CLI sign-in",
    "CLI サインイン",
    "CLI 로그인",
  ],
  "Sign-in status is reported by the isolated CLI worker; credential contents never enter the API.":
    [
      "登入狀態由獨立 cli-worker 回報，credential 內容不會進入 API。",
      "登录状态由独立 cli-worker 报告，credential 内容不会进入 API。",
      "Sign-in status is reported by the isolated CLI worker; credential contents never enter the API.",
      "サインイン状態は独立した cli-worker から報告され、credential の内容は API に入りません。",
      "로그인 상태는 독립된 cli-worker가 보고하며 credential 내용은 API로 전달되지 않습니다.",
    ],
  "Sign in through the Claude Code account flow; credentials stay in local ~/.claude and never enter the API.":
    [
      "透過 Claude Code 帳號流程登入，credential 存於本機 ~/.claude，不會進入 API。",
      "通过 Claude Code 账户流程登录，credential 保存在本地 ~/.claude，不会进入 API。",
      "Sign in through the Claude Code account flow; credentials stay in local ~/.claude and never enter the API.",
      "Claude Code アカウントフローでサインインします。credential はローカルの ~/.claude に保存され、API には入りません。",
      "Claude Code 계정 흐름으로 로그인하며 credential은 로컬 ~/.claude에 저장되고 API로 전달되지 않습니다.",
    ],
  "Test Codex": [
    "測試 Codex",
    "测试 Codex",
    "Test Codex",
    "Codex をテスト",
    "Codex 테스트",
  ],
  "Test Claude": [
    "測試 Claude",
    "测试 Claude",
    "Test Claude",
    "Claude をテスト",
    "Claude 테스트",
  ],
  "Start sign-in": [
    "開始登入",
    "开始登录",
    "Start sign-in",
    "サインイン開始",
    "로그인 시작",
  ],
  "Cancel sign-in": [
    "取消登入",
    "取消登录",
    "Cancel sign-in",
    "サインインをキャンセル",
    "로그인 취소",
  ],
  "Complete sign-in before testing": [
    "完成登入後才能測試",
    "完成登录后才能测试",
    "Complete sign-in before testing",
    "テスト前にサインインを完了してください",
    "테스트 전에 로그인을 완료하세요",
  ],
  "Sign out": ["登出", "退出登录", "Sign out", "サインアウト", "로그아웃"],
  "Not signed in. Complete account authorization on the sign-in page; testing is available after the status becomes Authenticated.":
    [
      "尚未登入。請完成登入頁的帳號授權；狀態變成 Authenticated 後才能測試。",
      "尚未登录。请在登录页面完成账户授权；状态变为 Authenticated 后才能测试。",
      "Not signed in. Complete account authorization on the sign-in page; testing is available after the status becomes Authenticated.",
      "未サインインです。サインインページでアカウント認証を完了してください。状態が Authenticated になるとテストできます。",
      "로그인되지 않았습니다. 로그인 페이지에서 계정 인증을 완료하세요. 상태가 Authenticated가 되면 테스트할 수 있습니다.",
    ],
  "After authorizing at the URL above, paste the code": [
    "開啟上方網址授權後，貼上取得的 code",
    "在上方网址授权后，粘贴获得的 code",
    "After authorizing at the URL above, paste the code",
    "上の URL で認証後、取得した code を貼り付け",
    "위 URL에서 인증한 후 받은 code를 붙여넣으세요",
  ],
  "Submit code": [
    "送出 code",
    "提交 code",
    "Submit code",
    "code を送信",
    "code 제출",
  ],
  "Sign in to the CLI used by the reasoning engine. Configure models and endpoints separately.":
    [
      "登入推理引擎使用的 CLI；模型與端點請另行設定。",
      "登录推理引擎使用的 CLI；模型与端点请单独设置。",
      "Sign in to the CLI used by the reasoning engine. Configure models and endpoints separately.",
      "推論エンジンが使用する CLI にサインインします。モデルとエンドポイントは別途設定してください。",
      "추론 엔진이 사용하는 CLI에 로그인합니다. 모델 및 엔드포인트는 별도로 설정하세요.",
    ],
  "Allow Engine CLI network access": [
    "允許 Engine CLI network access",
    "允许 Engine CLI network access",
    "Allow Engine CLI network access",
    "Engine CLI のネットワークアクセスを許可",
    "Engine CLI 네트워크 접근 허용",
  ],
  "System check": [
    "系統檢查",
    "系统检查",
    "System check",
    "システムチェック",
    "시스템 검사",
  ],
  "Engine sign-in": [
    "引擎登入",
    "引擎登录",
    "Engine sign-in",
    "エンジンサインイン",
    "엔진 로그인",
  ],
  "Reasoning engine": [
    "推理引擎",
    "推理引擎",
    "Reasoning engine",
    "推論エンジン",
    "추론 엔진",
  ],
  "STT settings": [
    "STT 設定",
    "STT 设置",
    "STT settings",
    "STT 設定",
    "STT 설정",
  ],
  "TTS settings": [
    "TTS 設定",
    "TTS 设置",
    "TTS settings",
    "TTS 設定",
    "TTS 설정",
  ],
  "Language settings": [
    "語言設定",
    "语言设置",
    "Language settings",
    "言語設定",
    "언어 설정",
  ],
  "Microphone test": [
    "麥克風測試",
    "麦克风测试",
    "Microphone test",
    "マイクテスト",
    "마이크 테스트",
  ],
  "Setup complete": [
    "儲存完成",
    "保存完成",
    "Setup complete",
    "セットアップ完了",
    "설정 완료",
  ],
  "Setup wizard": [
    "設定精靈",
    "设置向导",
    "Setup wizard",
    "セットアップウィザード",
    "설정 마법사",
  ],
  "Settings are stored in the backend; credentials remain only in the local CLI or environment secrets.":
    [
      "設定會儲存在後端；credential 僅留在本機 CLI 或環境 secret。",
      "设置保存在后端；credential 仅保留在本地 CLI 或环境 secret 中。",
      "Settings are stored in the backend; credentials remain only in the local CLI or environment secrets.",
      "設定はバックエンドに保存され、credential はローカル CLI または環境 secret にのみ残ります。",
      "설정은 백엔드에 저장되며 credential은 로컬 CLI 또는 환경 secret에만 남습니다.",
    ],
  "Checks actual service health for Compose, GPU, database, and tools.": [
    "由實際服務健康狀態確認 Compose、GPU、資料庫與工具鏈。",
    "通过实际服务健康状态检查 Compose、GPU、数据库和工具链。",
    "Checks actual service health for Compose, GPU, database, and tools.",
    "実際のサービス状態から Compose、GPU、データベース、ツールを確認します。",
    "실제 서비스 상태로 Compose, GPU, 데이터베이스 및 도구를 확인합니다.",
  ],
  Passed: ["通過", "通过", "Passed", "合格", "통과"],
  "Needs attention": [
    "需要處理",
    "需要处理",
    "Needs attention",
    "要対応",
    "조치 필요",
  ],
  "Verify/fix: {command}": [
    "確認／修復：{command}",
    "确认／修复：{command}",
    "Verify/fix: {command}",
    "確認／修復: {command}",
    "확인/수정: {command}",
  ],
  Recheck: ["重新檢查", "重新检查", "Recheck", "再チェック", "다시 검사"],
  Installed: ["已安裝", "已安装", "Installed", "インストール済み", "설치됨"],
  "Signed in": ["已登入", "已登录", "Signed in", "サインイン済み", "로그인됨"],
  "Signed out": [
    "尚未登入",
    "尚未登录",
    "Signed out",
    "未サインイン",
    "로그아웃됨",
  ],
  "The reasoning CLI is selected and signed in on the CLI sign-in page. Credentials remain in the local CLI.":
    [
      "推理 CLI 的選擇與登入皆在「CLI 登入」頁完成，credential 僅留在本機 CLI。",
      "推理 CLI 的选择与登录均在“CLI 登录”页面完成，credential 仅留在本地 CLI。",
      "The reasoning CLI is selected and signed in on the CLI sign-in page. Credentials remain in the local CLI.",
      "推論 CLI の選択とサインインは CLI サインインページで行い、credential はローカル CLI にのみ残ります。",
      "추론 CLI 선택 및 로그인은 CLI 로그인 페이지에서 수행하며 credential은 로컬 CLI에만 남습니다.",
    ],
  "Go to CLI sign-in": [
    "前往 CLI 登入",
    "前往 CLI 登录",
    "Go to CLI sign-in",
    "CLI サインインへ",
    "CLI 로그인으로 이동",
  ],
  "Manage the reasoning provider profile, model, sandbox, and network policy here.":
    [
      "在此管理 reasoning provider 的 profile、model、sandbox 與 network policy。",
      "在此管理 reasoning provider 的 profile、model、sandbox 和 network policy。",
      "Manage the reasoning provider profile, model, sandbox, and network policy here.",
      "ここで reasoning provider の profile、model、sandbox、network policy を管理します。",
      "여기에서 reasoning provider profile, model, sandbox 및 network policy를 관리합니다.",
    ],
  "No reasoning provider": [
    "尚無 reasoning provider",
    "尚无 reasoning provider",
    "No reasoning provider",
    "reasoning provider がありません",
    "reasoning provider 없음",
  ],
  "Manage providers": [
    "管理 Provider",
    "管理 Provider",
    "Manage providers",
    "Provider を管理",
    "Provider 관리",
  ],
  "Local faster-whisper prefers the A6000 and explicitly falls back to CPU on failure.":
    [
      "本機 faster-whisper 優先使用 A6000，失敗時明確切換 CPU fallback。",
      "本地 faster-whisper 优先使用 A6000，失败时明确切换 CPU fallback。",
      "Local faster-whisper prefers the A6000 and explicitly falls back to CPU on failure.",
      "ローカル faster-whisper は A6000 を優先し、失敗時は明示的に CPU へフォールバックします。",
      "로컬 faster-whisper는 A6000을 우선 사용하며 실패 시 명시적으로 CPU로 대체합니다.",
    ],
  "Not configured": [
    "未設定",
    "未设置",
    "Not configured",
    "未設定",
    "설정되지 않음",
  ],
  "Test STT provider": [
    "測試 STT Provider",
    "测试 STT Provider",
    "Test STT provider",
    "STT Provider をテスト",
    "STT Provider 테스트",
  ],
  "Browser speech is the fallback; server TTS can be selected from the provider registry.":
    [
      "瀏覽器語音為 fallback；server TTS 可從 Provider registry 選用。",
      "浏览器语音为 fallback；server TTS 可从 Provider registry 选择。",
      "Browser speech is the fallback; server TTS can be selected from the provider registry.",
      "ブラウザー音声がフォールバックで、server TTS は Provider registry から選択できます。",
      "브라우저 음성이 fallback이며 server TTS는 Provider registry에서 선택할 수 있습니다.",
    ],
  "Play test": [
    "播放測試",
    "播放测试",
    "Play test",
    "テスト再生",
    "테스트 재생",
  ],
  Stop: ["停止", "停止", "Stop", "停止", "중지"],
  "Test provider": [
    "測試 Provider",
    "测试 Provider",
    "Test provider",
    "Provider をテスト",
    "Provider 테스트",
  ],
  "Input, transcript, translation, suggestions, summary, export, and TTS languages are configured independently.":
    [
      "輸入、逐字稿、翻譯、建議、摘要、匯出與 TTS 語言可獨立設定。",
      "输入、转录、翻译、建议、摘要、导出和 TTS 语言可独立设置。",
      "Input, transcript, translation, suggestions, summary, export, and TTS languages are configured independently.",
      "入力、文字起こし、翻訳、提案、要約、エクスポート、TTS の言語を個別に設定できます。",
      "입력, 전사, 번역, 제안, 요약, 내보내기 및 TTS 언어를 독립적으로 설정할 수 있습니다.",
    ],
  "Suggestion output": [
    "建議輸出",
    "建议输出",
    "Suggestion output",
    "提案の出力",
    "제안 출력",
  ],
  "Summary output": [
    "摘要輸出",
    "摘要输出",
    "Summary output",
    "要約の出力",
    "요약 출력",
  ],
  "The browser shows live input level after permission; this test neither uploads nor saves audio.":
    [
      "瀏覽器取得權限後顯示即時音量；此測試不會上傳或保存音訊。",
      "浏览器获得权限后显示实时音量；此测试不会上传或保存音频。",
      "The browser shows live input level after permission; this test neither uploads nor saves audio.",
      "ブラウザーの許可後に入力レベルを表示します。このテストは音声をアップロードも保存もしません。",
      "브라우저 권한 허용 후 실시간 입력 레벨을 표시하며 오디오를 업로드하거나 저장하지 않습니다.",
    ],
  "Stop test": [
    "停止測試",
    "停止测试",
    "Stop test",
    "テスト停止",
    "테스트 중지",
  ],
  "Allow and test": [
    "允許並測試",
    "允许并测试",
    "Allow and test",
    "許可してテスト",
    "허용 및 테스트",
  ],
  "Save and start": [
    "儲存並開始使用",
    "保存并开始使用",
    "Save and start",
    "保存して開始",
    "저장하고 시작",
  ],
  "Core services are ready. You can change these settings later from Setup, CLI sign-in, and Models and endpoints.":
    [
      "所有基礎服務已可用。之後仍可從設定精靈、CLI 登入與模型端點重新調整。",
      "所有基础服务均可用。之后仍可从设置向导、CLI 登录和模型端点重新调整。",
      "Core services are ready. You can change these settings later from Setup, CLI sign-in, and Models and endpoints.",
      "基本サービスの準備が完了しました。後からセットアップ、CLI サインイン、モデルとエンドポイントで変更できます。",
      "핵심 서비스가 준비되었습니다. 나중에 설정, CLI 로그인 및 모델 및 엔드포인트에서 변경할 수 있습니다.",
    ],
  "Save and open workspace": [
    "儲存並開啟工作台",
    "保存并打开工作台",
    "Save and open workspace",
    "保存してワークスペースを開く",
    "저장하고 작업 공간 열기",
  ],
  Previous: ["上一步", "上一步", "Previous", "戻る", "이전"],
  Next: ["下一步", "下一步", "Next", "次へ", "다음"],
  "Speech test is working": [
    "Meeting Copilot 語音測試正常",
    "Meeting Copilot 语音测试正常",
    "Meeting Copilot speech test is working",
    "Meeting Copilot 音声テストは正常です",
    "Meeting Copilot 음성 테스트가 정상입니다",
  ],
  "Available {free} GB / {total} GB": [
    "可用 {free} GB / {total} GB",
    "可用 {free} GB / {total} GB",
    "Available {free} GB / {total} GB",
    "空き {free} GB / {total} GB",
    "사용 가능 {free} GB / {total} GB",
  ],
  "Creation failed": [
    "建立失敗",
    "创建失败",
    "Creation failed",
    "作成に失敗しました",
    "생성 실패",
  ],
  "Prepare new meeting": [
    "準備新會議",
    "准备新会议",
    "Prepare new meeting",
    "新しい会議を準備",
    "새 회의 준비",
  ],
  "Configure input, transcript, translation, analysis output, export, and speech languages independently.":
    [
      "獨立設定輸入、逐字稿、翻譯、分析輸出、匯出與語音語言。",
      "独立设置输入、转录、翻译、分析输出、导出和语音语言。",
      "Configure input, transcript, translation, analysis output, export, and speech languages independently.",
      "入力、文字起こし、翻訳、分析出力、エクスポート、音声言語を個別に設定します。",
      "입력, 전사, 번역, 분석 출력, 내보내기 및 음성 언어를 독립적으로 설정합니다.",
    ],
  "Meeting details": [
    "會議內容",
    "会议内容",
    "Meeting details",
    "会議内容",
    "회의 내용",
  ],
  Project: ["專案", "项目", "Project", "プロジェクト", "프로젝트"],
  "No project": [
    "不隸屬專案",
    "不属于项目",
    "No project",
    "プロジェクトなし",
    "프로젝트 없음",
  ],
  Title: ["標題", "标题", "Title", "タイトル", "제목"],
  Goal: ["目標", "目标", "Goal", "目標", "목표"],
  "Participants (comma-separated)": [
    "參與者（逗號分隔）",
    "参与者（逗号分隔）",
    "Participants (comma-separated)",
    "参加者（カンマ区切り）",
    "참가자(쉼표로 구분)",
  ],
  "Reference notes": [
    "參考筆記",
    "参考笔记",
    "Reference notes",
    "参考メモ",
    "참고 메모",
  ],
  "Original with available translation": [
    "原文 + 可用翻譯",
    "原文 + 可用翻译",
    "Original with available translation",
    "原文 + 利用可能な翻訳",
    "원문 + 사용 가능한 번역",
  ],
  "Analysis content": [
    "分析內容",
    "分析内容",
    "Analysis content",
    "分析内容",
    "분석 내용",
  ],
  "Original and translation": [
    "原文與翻譯",
    "原文与翻译",
    "Original and translation",
    "原文と翻訳",
    "원문 및 번역",
  ],
  "Audio and models": [
    "音訊與模型",
    "音频与模型",
    "Audio and models",
    "音声とモデル",
    "오디오 및 모델",
  ],
  "Analysis engine": [
    "分析引擎",
    "分析引擎",
    "Analysis engine",
    "分析エンジン",
    "분석 엔진",
  ],
  "Analysis interval (seconds)": [
    "分析間隔（秒）",
    "分析间隔（秒）",
    "Analysis interval (seconds)",
    "分析間隔（秒）",
    "분석 간격(초)",
  ],
  "Suggestion cooldown (seconds)": [
    "建議冷卻（秒）",
    "建议冷却（秒）",
    "Suggestion cooldown (seconds)",
    "提案クールダウン（秒）",
    "제안 대기 시간(초)",
  ],
  "Stop microphone test": [
    "停止麥克風測試",
    "停止麦克风测试",
    "Stop microphone test",
    "マイクテストを停止",
    "마이크 테스트 중지",
  ],
  "Policies and privacy": [
    "政策與隱私",
    "策略与隐私",
    "Policies and privacy",
    "ポリシーとプライバシー",
    "정책 및 개인정보",
  ],
  "Automatic analysis": [
    "自動分析",
    "自动分析",
    "Automatic analysis",
    "自動分析",
    "자동 분석",
  ],
  "Run Codex only when rules trigger and cooldown has elapsed": [
    "規則觸發且通過 cooldown 才執行 Codex",
    "仅在规则触发且 cooldown 结束后运行 Codex",
    "Run Codex only when rules trigger and cooldown has elapsed",
    "ルールが発火し cooldown 経過後にのみ Codex を実行",
    "규칙이 트리거되고 cooldown이 지난 경우에만 Codex 실행",
  ],
  "Automatically read AI suggestions": [
    "自動朗讀 AI 建議",
    "自动朗读 AI 建议",
    "Automatically read AI suggestions",
    "AI 提案を自動読み上げ",
    "AI 제안 자동 읽기",
  ],
  "Play each new suggestion immediately with the selected TTS": [
    "有新建議時立即使用所選 TTS 播放",
    "有新建议时立即使用所选 TTS 播放",
    "Play each new suggestion immediately with the selected TTS",
    "新しい提案を選択した TTS ですぐに再生",
    "새 제안을 선택한 TTS로 즉시 재생",
  ],
  "Save original audio": [
    "保存原始音訊",
    "保存原始音频",
    "Save original audio",
    "元の音声を保存",
    "원본 오디오 저장",
  ],
  "Off by default": [
    "預設關閉",
    "默认关闭",
    "Off by default",
    "既定ではオフ",
    "기본값 꺼짐",
  ],
  "Enable repository context": [
    "啟用 repository context",
    "启用 repository context",
    "Enable repository context",
    "repository context を有効化",
    "repository context 활성화",
  ],
  "Must be inside the backend allowlist and read-only": [
    "必須位於後端 allowlist 且唯讀",
    "必须位于后端 allowlist 且只读",
    "Must be inside the backend allowlist and read-only",
    "バックエンドの allowlist 内で読み取り専用である必要があります",
    "백엔드 allowlist 내부에 있고 읽기 전용이어야 합니다",
  ],
  "I have informed participants that microphone audio will be transcribed locally and agree to the storage settings above.":
    [
      "我已告知參與者麥克風音訊將在本機轉錄，並同意上述保存設定。",
      "我已告知参与者麦克风音频将在本地转录，并同意上述保存设置。",
      "I have informed participants that microphone audio will be transcribed locally and agree to the storage settings above.",
      "参加者にマイク音声がローカルで文字起こしされることを通知し、上記の保存設定に同意しました。",
      "참가자에게 마이크 오디오가 로컬에서 전사됨을 알렸으며 위 저장 설정에 동의합니다.",
    ],
  "Start meeting": [
    "開始會議",
    "开始会议",
    "Start meeting",
    "会議を開始",
    "회의 시작",
  ],
  "Unable to connect to audio service": [
    "無法連線到音訊服務",
    "无法连接到音频服务",
    "Unable to connect to audio service",
    "音声サービスに接続できません",
    "오디오 서비스에 연결할 수 없음",
  ],
  "Unable to start recording": [
    "無法開始錄音",
    "无法开始录音",
    "Unable to start recording",
    "録音を開始できません",
    "녹음을 시작할 수 없음",
  ],
  "Add manual suggestion": [
    "新增人工建議",
    "新增人工建议",
    "Add manual suggestion",
    "手動提案を追加",
    "수동 제안 추가",
  ],
  "Add a suggestion from a participant.": [
    "加入一則由與會者提出的建議。",
    "添加一条参与者提出的建议。",
    "Add a suggestion from a participant.",
    "参加者からの提案を追加します。",
    "참가자가 제시한 제안을 추가합니다.",
  ],
  "Suggestion content": [
    "建議內容",
    "建议内容",
    "Suggestion content",
    "提案内容",
    "제안 내용",
  ],
  Add: ["新增", "新增", "Add", "追加", "추가"],
  "Unable to play this suggestion automatically": [
    "無法自動播放這則建議",
    "无法自动播放此建议",
    "Unable to play this suggestion automatically",
    "この提案を自動再生できません",
    "이 제안을 자동 재생할 수 없음",
  ],
  "Start recording": [
    "開始錄音",
    "开始录音",
    "Start recording",
    "録音開始",
    "녹음 시작",
  ],
  Pause: ["暫停", "暂停", "Pause", "一時停止", "일시 중지"],
  Resume: ["繼續", "继续", "Resume", "再開", "계속"],
  End: ["結束", "结束", "End", "終了", "종료"],
  "Live transcript": [
    "即時逐字稿",
    "实时转录",
    "Live transcript",
    "リアルタイム文字起こし",
    "실시간 전사",
  ],
  Search: ["搜尋", "搜索", "Search", "検索", "검색"],
  "Auto-scroll": [
    "自動捲動",
    "自动滚动",
    "Auto-scroll",
    "自動スクロール",
    "자동 스크롤",
  ],
  "Listening; captions appear in about 4 seconds": [
    "正在聆聽，約 4 秒後顯示字幕",
    "正在聆听，约 4 秒后显示字幕",
    "Listening; captions appear in about 4 seconds",
    "リスニング中。約 4 秒後に字幕を表示します",
    "듣는 중이며 약 4초 후 자막이 표시됩니다",
  ],
  "Start recording to receive transcripts": [
    "按下開始錄音以接收逐字稿",
    "按下开始录音以接收转录",
    "Start recording to receive transcripts",
    "録音を開始して文字起こしを受信",
    "녹음을 시작하여 전사를 받으세요",
  ],
  "Edit source text": [
    "編輯原文",
    "编辑原文",
    "Edit source text",
    "原文を編集",
    "원문 편집",
  ],
  Pin: ["釘選", "置顶", "Pin", "ピン留め", "고정"],
  "AI suggestions": [
    "AI 建議",
    "AI 建议",
    "AI suggestions",
    "AI 提案",
    "AI 제안",
  ],
  "Auto-read": [
    "自動朗讀",
    "自动朗读",
    "Auto-read",
    "自動読み上げ",
    "자동 읽기",
  ],
  "Manual suggestion": [
    "人工建議",
    "人工建议",
    "Manual suggestion",
    "手動提案",
    "수동 제안",
  ],
  "Analyze now": [
    "立即分析",
    "立即分析",
    "Analyze now",
    "今すぐ分析",
    "지금 분석",
  ],
  "No suggestions yet": [
    "尚無建議",
    "暂无建议",
    "No suggestions yet",
    "提案はまだありません",
    "아직 제안 없음",
  ],
  "Codex displays content only when it adds meaningful new value.": [
    "Codex 只在有實質新價值時顯示內容。",
    "Codex 仅在有实质新价值时显示内容。",
    "Codex displays content only when it adds meaningful new value.",
    "Codex は実質的な新しい価値がある場合のみ内容を表示します。",
    "Codex는 실질적인 새 가치가 있을 때만 내용을 표시합니다.",
  ],
  Accept: ["接受", "接受", "Accept", "承認", "수락"],
  Ignore: ["忽略", "忽略", "Ignore", "無視", "무시"],
  Copy: ["複製", "复制", "Copy", "コピー", "복사"],
  "Edit suggestion": [
    "編輯建議",
    "编辑建议",
    "Edit suggestion",
    "提案を編集",
    "제안 편집",
  ],
  "Edit AI suggestion": [
    "編輯 AI 建議",
    "编辑 AI 建议",
    "Edit AI suggestion",
    "AI 提案を編集",
    "AI 제안 편집",
  ],
  "Update the suggestion and save it.": [
    "更新建議內容後儲存。",
    "更新建议内容后保存。",
    "Update the suggestion and save it.",
    "提案内容を更新して保存します。",
    "제안 내용을 업데이트하고 저장합니다.",
  ],
  Play: ["播放", "播放", "Play", "再生", "재생"],
  "Stop playback": [
    "停止播放",
    "停止播放",
    "Stop playback",
    "再生停止",
    "재생 중지",
  ],
  "Ask about the current discussion…": [
    "針對目前討論提出問題…",
    "针对当前讨论提出问题…",
    "Ask about the current discussion…",
    "現在の議論について質問…",
    "현재 논의에 대해 질문…",
  ],
  Send: ["送出", "发送", "Send", "送信", "보내기"],
  "Meeting state": [
    "會議狀態",
    "会议状态",
    "Meeting state",
    "会議状態",
    "회의 상태",
  ],
  "Open questions": [
    "未解問題",
    "未解决问题",
    "Open questions",
    "未解決の質問",
    "미해결 질문",
  ],
  Risks: ["風險", "风险", "Risks", "リスク", "위험"],
  Decision: ["決策", "决策", "Decision", "決定", "결정"],
  "Open question": [
    "未解問題",
    "未解问题",
    "Open question",
    "未解決の質問",
    "미해결 질문",
  ],
  Risk: ["風險", "风险", "Risk", "リスク", "위험"],
  "Action item": [
    "行動項目",
    "行动项目",
    "Action item",
    "アクション項目",
    "작업 항목",
  ],
  "{count} seconds": [
    "{count} 秒",
    "{count} 秒",
    "{count} seconds",
    "{count} 秒",
    "{count}초",
  ],
  "{count} minutes": [
    "{count} 分",
    "{count} 分钟",
    "{count} minutes",
    "{count} 分",
    "{count}분",
  ],
  "{count} hours": [
    "{count} 小時",
    "{count} 小时",
    "{count} hours",
    "{count} 時間",
    "{count}시간",
  ],
  Calculating: ["計算中", "计算中", "Calculating", "計算中", "계산 중"],
  "Unable to calculate analytics": [
    "無法計算分析",
    "无法计算分析",
    "Unable to calculate analytics",
    "分析を計算できません",
    "분석을 계산할 수 없음",
  ],
  "All figures are calculated directly from the database without the reasoning engine. Duration source:":
    [
      "所有數字直接由資料庫統計，未經由推理引擎產生。時長來源：",
      "所有数字均直接从数据库统计，不经推理引擎生成。时长来源：",
      "All figures are calculated directly from the database without the reasoning engine. Duration source:",
      "すべての数値は推論エンジンを使わずデータベースから直接集計しています。時間の出典：",
      "모든 수치는 추론 엔진 없이 데이터베이스에서 직접 계산됩니다. 시간 출처:",
    ],
  "meeting start and end times": [
    "會議起訖時間",
    "会议起止时间",
    "meeting start and end times",
    "会議の開始・終了時刻",
    "회의 시작 및 종료 시간",
  ],
  "transcript timeline (estimated)": [
    "逐字稿時間軸（估算）",
    "转录时间轴（估算）",
    "transcript timeline (estimated)",
    "文字起こしのタイムライン（推定）",
    "전사 타임라인(추정)",
  ],
  "Meeting duration": [
    "會議時長",
    "会议时长",
    "Meeting duration",
    "会議時間",
    "회의 시간",
  ],
  "Transcript characters": [
    "逐字稿字數",
    "转录字符数",
    "Transcript characters",
    "文字起こし文字数",
    "전사 문자 수",
  ],
  "Overdue actions": [
    "逾期行動",
    "逾期行动",
    "Overdue actions",
    "期限超過の項目",
    "기한 초과 작업",
  ],
  "Unresolved questions": [
    "未解決問題",
    "未解决问题",
    "Unresolved questions",
    "未解決の質問",
    "미해결 질문",
  ],
  "Suggestion handling": [
    "建議處理",
    "建议处理",
    "Suggestion handling",
    "提案の処理",
    "제안 처리",
  ],
  Total: ["總數", "总数", "Total", "合計", "합계"],
  accepted: ["已接受", "已接受", "accepted", "承認済み", "수락됨"],
  edited: ["已編輯", "已编辑", "edited", "編集済み", "편집됨"],
  converted: ["已轉換", "已转换", "converted", "変換済み", "변환됨"],
  ignored: ["已忽略", "已忽略", "ignored", "無視", "무시됨"],
  "Action quality": [
    "行動品質",
    "行动质量",
    "Action quality",
    "アクション品質",
    "작업 품질",
  ],
  "With owner": [
    "有負責人",
    "有负责人",
    "With owner",
    "担当者あり",
    "담당자 있음",
  ],
  "With due date": [
    "有期限",
    "有期限",
    "With due date",
    "期限あり",
    "기한 있음",
  ],
  Completed: ["已完成", "已完成", "Completed", "完了", "완료됨"],
  "Average completion time": [
    "平均完成時間",
    "平均完成时间",
    "Average completion time",
    "平均完了時間",
    "평균 완료 시간",
  ],
  "Decisions per hour": [
    "每小時決策數",
    "每小时决策数",
    "Decisions per hour",
    "1時間あたりの決定数",
    "시간당 결정 수",
  ],
  "Engine runs": [
    "引擎執行",
    "引擎运行",
    "Engine runs",
    "エンジン実行",
    "엔진 실행",
  ],
  Runs: ["次數", "次数", "Runs", "回数", "실행 횟수"],
  "Average duration": [
    "平均耗時",
    "平均耗时",
    "Average duration",
    "平均所要時間",
    "평균 소요 시간",
  ],
  "Failure rate": ["失敗率", "失败率", "Failure rate", "失敗率", "실패율"],
  "Timeout rate": [
    "逾時率",
    "超时率",
    "Timeout rate",
    "タイムアウト率",
    "시간 초과율",
  ],
  "Speaking time": [
    "發言時間",
    "发言时间",
    "Speaking time",
    "発言時間",
    "발언 시간",
  ],
  "Only speaker-labelled segments are included": [
    "僅涵蓋已標記講者的段落",
    "仅包含已标记说话人的段落",
    "Only speaker-labelled segments are included",
    "話者ラベル付きの区間のみ対象です",
    "화자 표시가 있는 구간만 포함됩니다",
  ],
  "The system does not separate speakers automatically.": [
    "系統沒有自動分離講者。",
    "系统不会自动分离说话人。",
    "The system does not separate speakers automatically.",
    "システムは話者を自動分離しません。",
    "시스템은 화자를 자동으로 분리하지 않습니다.",
  ],
  "The transcript has no speaker labels, so speaking share cannot be calculated.":
    [
      "逐字稿沒有講者標記，無法計算發言比例。",
      "转录没有说话人标记，无法计算发言比例。",
      "The transcript has no speaker labels, so speaking share cannot be calculated.",
      "文字起こしに話者ラベルがないため、発言割合を計算できません。",
      "전사에 화자 표시가 없어 발언 비율을 계산할 수 없습니다.",
    ],
  "Meeting history": [
    "會議歷史",
    "会议历史",
    "Meeting history",
    "会議履歴",
    "회의 기록",
  ],
  "Review transcripts, decisions, Codex runs, and exports.": [
    "檢視逐字稿、決策、Codex runs 與匯出。",
    "查看转录、决策、Codex 运行和导出。",
    "Review transcripts, decisions, Codex runs, and exports.",
    "文字起こし、決定、Codex 実行、エクスポートを確認します。",
    "전사, 결정, Codex 실행 및 내보내기를 검토합니다.",
  ],
  "Search by title": [
    "依標題搜尋",
    "按标题搜索",
    "Search by title",
    "タイトルで検索",
    "제목으로 검색",
  ],
  Meeting: ["會議", "会议", "Meeting", "会議", "회의"],
  Status: ["狀態", "状态", "Status", "ステータス", "상태"],
  "Start time": ["開始時間", "开始时间", "Start time", "開始時刻", "시작 시간"],
  Language: ["語言", "语言", "Language", "言語", "언어"],
  "Not started": ["尚未開始", "尚未开始", "Not started", "未開始", "시작 전"],
  "No meetings found": [
    "找不到會議",
    "找不到会议",
    "No meetings found",
    "会議が見つかりません",
    "회의를 찾을 수 없음",
  ],
  "Delete meeting": [
    "刪除會議",
    "删除会议",
    "Delete meeting",
    "会議を削除",
    "회의 삭제",
  ],
  "Permanently delete this meeting, transcript, and events? This cannot be undone.":
    [
      "完整刪除此會議、逐字稿與事件？此操作無法復原。",
      "永久删除此会议、转录和事件？此操作无法撤销。",
      "Permanently delete this meeting, transcript, and events? This cannot be undone.",
      "この会議、文字起こし、イベントを完全に削除しますか？元に戻せません。",
      "이 회의, 전사 및 이벤트를 영구 삭제하시겠습니까? 취소할 수 없습니다.",
    ],
  "Delete permanently": [
    "永久刪除",
    "永久删除",
    "Delete permanently",
    "完全に削除",
    "영구 삭제",
  ],
  "Analyze again": [
    "重新分析",
    "重新分析",
    "Analyze again",
    "再分析",
    "다시 분석",
  ],
  Transcript: ["逐字稿", "转录", "Transcript", "文字起こし", "전사"],
  "Suggestion acceptance rate": [
    "建議接受率",
    "建议接受率",
    "Suggestion acceptance rate",
    "提案承認率",
    "제안 수락률",
  ],
  transcript: ["逐字稿", "转录", "Transcript", "文字起こし", "전사"],
  suggestions: ["建議", "建议", "Suggestions", "提案", "제안"],
  state: ["狀態", "状态", "State", "状態", "상태"],
  analytics: ["分析", "分析", "Analytics", "分析", "분석"],
  Export: ["匯出", "导出", "Export", "エクスポート", "내보내기"],
  "Delete meeting audio": [
    "刪除會議音訊",
    "删除会议音频",
    "Delete meeting audio",
    "会議音声を削除",
    "회의 오디오 삭제",
  ],
  "Delete the saved original audio? The transcript and meeting data will remain.":
    [
      "刪除已保存的原始音訊？逐字稿與會議資料會保留。",
      "删除已保存的原始音频？转录和会议数据将保留。",
      "Delete the saved original audio? The transcript and meeting data will remain.",
      "保存された元音声を削除しますか？文字起こしと会議データは残ります。",
      "저장된 원본 오디오를 삭제하시겠습니까? 전사 및 회의 데이터는 유지됩니다.",
    ],
  "Delete audio": [
    "刪除音訊",
    "删除音频",
    "Delete audio",
    "音声を削除",
    "오디오 삭제",
  ],
  "Delete audio only": [
    "僅刪除音訊",
    "仅删除音频",
    "Delete audio only",
    "音声のみ削除",
    "오디오만 삭제",
  ],
  "Save failed": [
    "儲存失敗",
    "保存失败",
    "Save failed",
    "保存に失敗しました",
    "저장 실패",
  ],
  "Delete project": [
    "刪除專案",
    "删除项目",
    "Delete project",
    "プロジェクトを削除",
    "프로젝트 삭제",
  ],
  "Delete project “{name}” and its glossary and memory? Meetings will remain.":
    [
      "刪除專案「{name}」及其術語與記憶？會議會保留。",
      "删除项目“{name}”及其术语和记忆？会议将保留。",
      "Delete project “{name}” and its glossary and memory? Meetings will remain.",
      "プロジェクト「{name}」と用語集・メモリを削除しますか？会議は残ります。",
      "프로젝트 “{name}” 및 용어집과 메모리를 삭제하시겠습니까? 회의는 유지됩니다.",
    ],
  Delete: ["刪除", "删除", "Delete", "削除", "삭제"],
  Projects: ["專案", "项目", "Projects", "プロジェクト", "프로젝트"],
  "Manage goals, terminology, and long-term memory across meetings.": [
    "集中管理跨會議目標、術語與長期記憶。",
    "集中管理跨会议目标、术语和长期记忆。",
    "Manage goals, terminology, and long-term memory across meetings.",
    "会議をまたぐ目標、用語、長期メモリを管理します。",
    "회의 전반의 목표, 용어 및 장기 메모리를 관리합니다.",
  ],
  "New project": [
    "新增專案",
    "新增项目",
    "New project",
    "新規プロジェクト",
    "새 프로젝트",
  ],
  "Search projects": [
    "搜尋專案",
    "搜索项目",
    "Search projects",
    "プロジェクトを検索",
    "프로젝트 검색",
  ],
  "{count} projects": [
    "{count} 個專案",
    "{count} 个项目",
    "{count} projects",
    "{count} 件のプロジェクト",
    "프로젝트 {count}개",
  ],
  "No project description": [
    "尚未填寫專案說明",
    "尚未填写项目说明",
    "No project description",
    "プロジェクト説明なし",
    "프로젝트 설명 없음",
  ],
  Updated: ["更新", "更新", "Updated", "更新日", "업데이트"],
  "Open dashboard": [
    "開啟儀表板",
    "打开仪表板",
    "Open dashboard",
    "ダッシュボードを開く",
    "대시보드 열기",
  ],
  "Edit project": [
    "編輯專案",
    "编辑项目",
    "Edit project",
    "プロジェクトを編集",
    "프로젝트 편집",
  ],
  "No matching projects": [
    "尚無符合的專案",
    "没有符合的项目",
    "No matching projects",
    "一致するプロジェクトはありません",
    "일치하는 프로젝트 없음",
  ],
  "Create first project": [
    "建立第一個專案",
    "创建第一个项目",
    "Create first project",
    "最初のプロジェクトを作成",
    "첫 프로젝트 만들기",
  ],
  Description: ["說明", "说明", "Description", "説明", "설명"],
  "Default language": [
    "預設語言",
    "默认语言",
    "Default language",
    "既定の言語",
    "기본 언어",
  ],
  "Non-goals": ["非目標", "非目标", "Non-goals", "対象外", "비목표"],
  "Delete term": [
    "刪除術語",
    "删除术语",
    "Delete term",
    "用語を削除",
    "용어 삭제",
  ],
  "Delete term “{name}”?": [
    "刪除術語「{name}」？",
    "删除术语“{name}”？",
    "Delete term “{name}”?",
    "用語「{name}」を削除しますか？",
    "용어 “{name}”을 삭제하시겠습니까?",
  ],
  "Permanently delete project memory": [
    "永久刪除專案記憶",
    "永久删除项目记忆",
    "Permanently delete project memory",
    "プロジェクトメモリを完全に削除",
    "프로젝트 메모리 영구 삭제",
  ],
  "Permanently delete memory “{name}”? This cannot be undone.": [
    "永久刪除記憶「{name}」？此操作無法復原。",
    "永久删除记忆“{name}”？此操作无法撤销。",
    "Permanently delete memory “{name}”? This cannot be undone.",
    "メモリ「{name}」を完全に削除しますか？元に戻せません。",
    "메모리 “{name}”을 영구 삭제하시겠습니까? 취소할 수 없습니다.",
  ],
  "Loading project": [
    "載入專案",
    "加载项目",
    "Loading project",
    "プロジェクトを読み込み中",
    "프로젝트 로드 중",
  ],
  "Project not found": [
    "專案不存在",
    "项目不存在",
    "Project not found",
    "プロジェクトが見つかりません",
    "프로젝트를 찾을 수 없음",
  ],
  "No description": [
    "尚未填寫說明",
    "尚未填写说明",
    "No description",
    "説明なし",
    "설명 없음",
  ],
  "Project memory": [
    "專案記憶",
    "项目记忆",
    "Project memory",
    "プロジェクトメモリ",
    "프로젝트 메모리",
  ],
  Terms: ["術語", "术语", "Terms", "用語", "용어"],
  overview: ["總覽", "总览", "Overview", "概要", "개요"],
  memory: ["記憶", "记忆", "Memory", "メモリ", "메모리"],
  glossary: ["術語", "术语", "Glossary", "用語集", "용어집"],
  "Project goals": [
    "專案目標",
    "项目目标",
    "Project goals",
    "プロジェクト目標",
    "프로젝트 목표",
  ],
  "Recent meetings": [
    "最近會議",
    "最近会议",
    "Recent meetings",
    "最近の会議",
    "최근 회의",
  ],
  "No meetings yet": [
    "尚無會議",
    "暂无会议",
    "No meetings yet",
    "会議はまだありません",
    "아직 회의 없음",
  ],
  "Search memory": [
    "搜尋記憶",
    "搜索记忆",
    "Search memory",
    "メモリを検索",
    "메모리 검색",
  ],
  "Search terms": [
    "搜尋術語",
    "搜索术语",
    "Search terms",
    "用語を検索",
    "용어 검색",
  ],
  "Add memory": [
    "新增記憶",
    "新增记忆",
    "Add memory",
    "メモリを追加",
    "메모리 추가",
  ],
  "Add term": ["新增術語", "新增术语", "Add term", "用語を追加", "용어 추가"],
  Archive: ["封存", "归档", "Archive", "アーカイブ", "보관"],
  "No matching project memory": [
    "沒有符合的專案記憶",
    "没有符合的项目记忆",
    "No matching project memory",
    "一致するプロジェクトメモリはありません",
    "일치하는 프로젝트 메모리 없음",
  ],
  Term: ["術語", "术语", "Term", "用語", "용어"],
  "Preferred spelling / translation": [
    "偏好拼法 / 翻譯",
    "首选拼写 / 翻译",
    "Preferred spelling / translation",
    "優先表記 / 翻訳",
    "선호 표기 / 번역",
  ],
  Rules: ["規則", "规则", "Rules", "ルール", "규칙"],
  "Do not translate": [
    "禁止翻譯",
    "禁止翻译",
    "Do not translate",
    "翻訳禁止",
    "번역 금지",
  ],
  Translatable: ["可翻譯", "可翻译", "Translatable", "翻訳可", "번역 가능"],
  "No matching terms": [
    "沒有符合的術語",
    "没有符合的术语",
    "No matching terms",
    "一致する用語はありません",
    "일치하는 용어 없음",
  ],
  "Edit term": ["編輯術語", "编辑术语", "Edit term", "用語を編集", "용어 편집"],
  "Preferred spelling": [
    "偏好拼法",
    "首选拼写",
    "Preferred spelling",
    "優先表記",
    "선호 표기",
  ],
  Translation: ["翻譯", "翻译", "Translation", "翻訳", "번역"],
  "Aliases (comma-separated)": [
    "別名（逗號分隔）",
    "别名（逗号分隔）",
    "Aliases (comma-separated)",
    "別名（カンマ区切り）",
    "별칭(쉼표로 구분)",
  ],
  "Do not translate this term": [
    "禁止翻譯此術語",
    "禁止翻译此术语",
    "Do not translate this term",
    "この用語を翻訳しない",
    "이 용어 번역 금지",
  ],
  "Edit project memory": [
    "編輯專案記憶",
    "编辑项目记忆",
    "Edit project memory",
    "プロジェクトメモリを編集",
    "프로젝트 메모리 편집",
  ],
  "Add project memory": [
    "新增專案記憶",
    "新增项目记忆",
    "Add project memory",
    "プロジェクトメモリを追加",
    "프로젝트 메모리 추가",
  ],
  Category: ["分類", "分类", "Category", "カテゴリ", "분류"],
  Confidence: ["信心值", "置信度", "Confidence", "信頼度", "신뢰도"],
  "Back to projects": [
    "返回專案列表",
    "返回项目列表",
    "Back to projects",
    "プロジェクト一覧へ戻る",
    "프로젝트 목록으로 돌아가기",
  ],
  "Decision timeline": [
    "決策時間軸",
    "决策时间线",
    "Decision timeline",
    "決定タイムライン",
    "결정 타임라인",
  ],
  "Preserve every decision version, source meeting, and status transition.": [
    "保留每一版決策、來源會議與狀態轉換。",
    "保留每个决策版本、来源会议和状态转换。",
    "Preserve every decision version, source meeting, and status transition.",
    "すべての決定版、出典会議、状態遷移を保持します。",
    "모든 결정 버전, 출처 회의 및 상태 전환을 보존합니다.",
  ],
  "Add decision": [
    "新增決策",
    "新增决策",
    "Add decision",
    "決定を追加",
    "결정 추가",
  ],
  "Search title or content": [
    "搜尋標題或內容",
    "搜索标题或内容",
    "Search title or content",
    "タイトルまたは内容を検索",
    "제목 또는 내용 검색",
  ],
  "All projects": [
    "所有專案",
    "所有项目",
    "All projects",
    "すべてのプロジェクト",
    "모든 프로젝트",
  ],
  "All statuses": [
    "所有狀態",
    "所有状态",
    "All statuses",
    "すべての状態",
    "모든 상태",
  ],
  Owner: ["負責人", "负责人", "Owner", "担当者", "담당자"],
  "Confirm decision": [
    "確認決策",
    "确认决策",
    "Confirm decision",
    "決定を確定",
    "결정 확인",
  ],
  "Reject decision": [
    "拒絕決策",
    "拒绝决策",
    "Reject decision",
    "決定を却下",
    "결정 거부",
  ],
  "Create new version": [
    "建立新版",
    "创建新版本",
    "Create new version",
    "新版を作成",
    "새 버전 만들기",
  ],
  "No matching decisions": [
    "沒有符合的決策",
    "没有符合的决策",
    "No matching decisions",
    "一致する決定はありません",
    "일치하는 결정 없음",
  ],
  Version: ["版本", "版本", "Version", "バージョン", "버전"],
  Unassigned: ["未指派", "未分配", "Unassigned", "未割り当て", "미지정"],
  "Source meeting": [
    "來源會議",
    "来源会议",
    "Source meeting",
    "出典会議",
    "출처 회의",
  ],
  "Adjacent versions": [
    "相鄰版本",
    "相邻版本",
    "Adjacent versions",
    "前後のバージョン",
    "인접 버전",
  ],
  "Create v{version}": [
    "建立 v{version}",
    "创建 v{version}",
    "Create v{version}",
    "v{version} を作成",
    "v{version} 만들기",
  ],
  "Select meeting": [
    "選擇會議",
    "选择会议",
    "Select meeting",
    "会議を選択",
    "회의 선택",
  ],
  "Delete action item": [
    "刪除行動項目",
    "删除行动项目",
    "Delete action item",
    "アクション項目を削除",
    "작업 항목 삭제",
  ],
  "Delete action item “{name}”?": [
    "刪除行動項目「{name}」？",
    "删除行动项目“{name}”？",
    "Delete action item “{name}”?",
    "アクション項目「{name}」を削除しますか？",
    "작업 항목 “{name}”을 삭제하시겠습니까?",
  ],
  "Action items": [
    "行動項目",
    "行动项目",
    "Action items",
    "アクション項目",
    "작업 항목",
  ],
  "Track work by owner, due date, priority, and status.": [
    "依負責人、期限、優先度與狀態追蹤工作。",
    "按负责人、期限、优先级和状态跟踪工作。",
    "Track work by owner, due date, priority, and status.",
    "担当者、期限、優先度、状態で作業を追跡します。",
    "담당자, 기한, 우선순위 및 상태별로 작업을 추적합니다.",
  ],
  "Add item": ["新增項目", "新增项目", "Add item", "項目を追加", "항목 추가"],
  all: ["全部", "全部", "All", "すべて", "전체"],
  mine: ["我的", "我的", "Mine", "自分", "내 항목"],
  overdue: ["逾期", "逾期", "Overdue", "期限超過", "기한 초과"],
  due_soon: ["即將到期", "即将到期", "Due soon", "期限間近", "마감 임박"],
  in_progress: ["進行中", "进行中", "In progress", "進行中", "진행 중"],
  blocked: ["受阻", "受阻", "Blocked", "ブロック中", "차단됨"],
  completed: ["已完成", "已完成", "Completed", "完了", "완료됨"],
  "Search work or owner": [
    "搜尋工作或負責人",
    "搜索工作或负责人",
    "Search work or owner",
    "作業または担当者を検索",
    "작업 또는 담당자 검색",
  ],
  "{count} items": [
    "{count} 項",
    "{count} 项",
    "{count} items",
    "{count} 件",
    "{count}개 항목",
  ],
  Work: ["工作", "工作", "Work", "作業", "작업"],
  Due: ["到期", "到期", "Due", "期限", "기한"],
  Priority: ["優先度", "优先级", "Priority", "優先度", "우선순위"],
  "{name} status": [
    "{name} 狀態",
    "{name} 状态",
    "{name} status",
    "{name} の状態",
    "{name} 상태",
  ],
  "No action items in this view": [
    "此檢視沒有行動項目",
    "此视图没有行动项目",
    "No action items in this view",
    "この表示にアクション項目はありません",
    "이 보기에 작업 항목 없음",
  ],
  "Edit action item": [
    "編輯行動項目",
    "编辑行动项目",
    "Edit action item",
    "アクション項目を編集",
    "작업 항목 편집",
  ],
  "Add action item": [
    "新增行動項目",
    "新增行动项目",
    "Add action item",
    "アクション項目を追加",
    "작업 항목 추가",
  ],
  "Due date": ["到期日", "到期日", "Due date", "期限日", "마감일"],
  "Linked decision": [
    "連結決策",
    "关联决策",
    "Linked decision",
    "関連する決定",
    "연결된 결정",
  ],
  "Not linked": ["未連結", "未关联", "Not linked", "未関連", "연결 안 됨"],
  "Delete knowledge document": [
    "刪除知識文件",
    "删除知识文档",
    "Delete knowledge document",
    "ナレッジ文書を削除",
    "지식 문서 삭제",
  ],
  "Delete document “{name}” and its indexed content?": [
    "刪除文件「{name}」及其索引內容？",
    "删除文档“{name}”及其索引内容？",
    "Delete document “{name}” and its indexed content?",
    "文書「{name}」と索引内容を削除しますか？",
    "문서 “{name}” 및 색인된 내용을 삭제하시겠습니까?",
  ],
  "Knowledge base": [
    "知識庫",
    "知识库",
    "Knowledge base",
    "ナレッジベース",
    "지식 베이스",
  ],
  "Search meetings, transcripts, decisions, tasks, project memory, and documents.":
    [
      "搜尋會議、逐字稿、決策、任務、專案記憶與文件。",
      "搜索会议、转录、决策、任务、项目记忆和文档。",
      "Search meetings, transcripts, decisions, tasks, project memory, and documents.",
      "会議、文字起こし、決定、タスク、プロジェクトメモリ、文書を検索します。",
      "회의, 전사, 결정, 작업, 프로젝트 메모리 및 문서를 검색합니다.",
    ],
  "Add document": [
    "新增文件",
    "新增文档",
    "Add document",
    "文書を追加",
    "문서 추가",
  ],
  "Search all knowledge sources": [
    "搜尋全部知識來源",
    "搜索所有知识来源",
    "Search all knowledge sources",
    "すべてのナレッジソースを検索",
    "모든 지식 소스 검색",
  ],
  "All sources": [
    "所有來源",
    "所有来源",
    "All sources",
    "すべてのソース",
    "모든 소스",
  ],
  "No summary": ["沒有摘要", "没有摘要", "No summary", "要約なし", "요약 없음"],
  "No matching knowledge found": [
    "找不到符合的知識",
    "找不到符合的知识",
    "No matching knowledge found",
    "一致するナレッジが見つかりません",
    "일치하는 지식 없음",
  ],
  "Created date": ["建立日期", "创建日期", "Created date", "作成日", "생성일"],
  "Delete document": [
    "刪除文件",
    "删除文档",
    "Delete document",
    "文書を削除",
    "문서 삭제",
  ],
  "Add knowledge document": [
    "新增知識文件",
    "新增知识文档",
    "Add knowledge document",
    "ナレッジ文書を追加",
    "지식 문서 추가",
  ],
  "Global knowledge": [
    "全域知識",
    "全局知识",
    "Global knowledge",
    "グローバルナレッジ",
    "전역 지식",
  ],
  "Create index": [
    "建立索引",
    "创建索引",
    "Create index",
    "索引を作成",
    "색인 생성",
  ],
  "Codex runs": [
    "Codex 執行",
    "Codex 运行",
    "Codex runs",
    "Codex 実行",
    "Codex 실행",
  ],
  "Speech rate and volume test": [
    "語音速率與音量測試",
    "语音速率与音量测试",
    "Speech rate and volume test",
    "音声速度と音量のテスト",
    "음성 속도 및 볼륨 테스트",
  ],
} as const satisfies Record<string, Translation>;

export type PhraseKey = keyof typeof phrases;

const languageIndex: Record<LanguageCode, number> = {
  "zh-TW": 0,
  "zh-CN": 1,
  en: 2,
  ja: 3,
  ko: 4,
};

export function translatePhrase(
  key: PhraseKey,
  language: LanguageCode,
): string {
  return phrases[key][languageIndex[language]]!;
}
